# Phase 1B D11-D13 Acceptance Notebook

Human-readable acceptance checks for walk-forward integrity, the post-hoc DSR heuristic screen, and additional baseline strategies.

## 0. Setup

In [1]:
from pathlib import Path
from datetime import date, datetime, timezone
import os
import json
import sqlite3
import subprocess
import sys

import numpy as np
import pandas as pd
import yaml
from IPython.display import display



def _bootstrap_repo_root():
    start = Path.cwd().resolve()
    for candidate in (start, *start.parents):
        if (candidate / "pyproject.toml").exists() and (candidate / "backtest").exists():
            if str(candidate) not in sys.path:
                sys.path.insert(0, str(candidate))
            os.chdir(candidate)
            return candidate
    raise RuntimeError(f"Could not locate repo root from {start}")


PROJECT_ROOT = _bootstrap_repo_root()
print("Notebook repo root:", PROJECT_ROOT)

pd.set_option("display.max_columns", 40)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 160)

DB_PATH = PROJECT_ROOT / "backtest" / "experiments.db"
RESULTS_DIR = PROJECT_ROOT / "data" / "results"
PARQUET_PATH = PROJECT_ROOT / "data" / "raw" / "btcusdt_1h.parquet"
ENV_PATH = PROJECT_ROOT / "config" / "environments.yaml"

assert PARQUET_PATH.exists(), f"Missing canonical parquet: {PARQUET_PATH}"
assert ENV_PATH.exists(), f"Missing environments.yaml: {ENV_PATH}"

D11_ACCEPTANCE = {}


def pass_fail(condition):
    return "PASS" if bool(condition) else "FAIL"


def display_check_table(rows, title=None, require_all=True):
    checks = pd.DataFrame(rows)
    if title:
        print(title)
    display(checks)
    if require_all:
        failed = checks[checks["status"] != "PASS"]
        assert failed.empty, failed
    return checks


def check_row(check, passed, detail=""):
    return {"check": check, "status": pass_fail(passed), "detail": detail}


def read_runs_query(query, params=None):
    assert DB_PATH.exists(), f"experiments.db not found: {DB_PATH}"
    with sqlite3.connect(DB_PATH) as conn:
        return pd.read_sql_query(query, conn, params=params or ())

## A. Run Real Walk-Forward

This is the real D11 acceptance run. It uses the CLI path so the behavior matches the user-facing command:

```bash
python -m backtest.engine --strategy sma_crossover --mode walk-forward
```

The command writes a `walk_forward_summary` row plus one `walk_forward_window` row per generated window into `backtest/experiments.db`.

In [2]:
RUN_WALK_FORWARD = True

walk_forward_command = [
    sys.executable,
    "-m",
    "backtest.engine",
    "--strategy",
    "sma_crossover",
    "--mode",
    "walk-forward",
]

if RUN_WALK_FORWARD:
    completed = subprocess.run(walk_forward_command, capture_output=True, text=True)
    print(completed.stdout)
    if completed.stderr:
        print(completed.stderr)
    assert completed.returncode == 0, "Walk-forward CLI run failed"
else:
    print("Walk-forward run skipped. Set RUN_WALK_FORWARD = True for D11 acceptance.")

D11_ACCEPTANCE["walk_forward_cli_run"] = RUN_WALK_FORWARD

============================================================
WALK-FORWARD SUMMARY
============================================================
Summary ID:   92eb97ae...
Strategy:     sma_crossover
Windows:      20
============================================================
Mean Return:    0.3748 (37.48%)
Mean Sharpe:    -0.178
Worst Drawdown: 0.4366 (43.66%)
Total Trades:   513
Win Rate:       0.32
Profit Factor:  1.07
============================================================

Window   Train Period             Test Period               Trades   Return   Sharpe
-------- ------------------------ ------------------------ ------- -------- --------
  1      2020-01-01 to 2020-12-31 2021-01-01 to 2021-03-31     128   2.7109    2.240
  2      2020-04-01 to 2021-03-31 2021-04-01 to 2021-06-30     123   1.5435    1.656
  3      2020-07-01 to 2021-06-30 2021-07-01 to 2021-09-30     123   0.9169    1.230
  4      2020-10-01 to 2021-09-30 2021-10-01 to 2021-12-31     121   1.1132    1.357
  5      2021-01-01 to 2021-12-31 2022-01-01 to 2022-03-31     121   0.0103    0.282
  6      2021-04-01 to 2022-03-31 2022-04-01 to 2022-06-30     127  -0.5748   -1.265
  7      2021-07-01 to 2022-06-30 2022-07-01 to 2022-09-30     128  -0.3488   -0.569
  8      2021-10-01 to 2022-09-30 2022-10-01 to 2022-12-31     132  -0.4424   -1.004
  9      2022-01-01 to 2022-12-31 2023-01-01 to 2023-03-31     130  -0.0497    0.094
  10     2022-04-01 to 2023-03-31 2023-04-01 to 2023-06-30     136  -0.0808    0.002
  11     2022-07-01 to 2023-06-30 2023-07-01 to 2023-09-30     146   0.2827    0.756
  12     2022-10-01 to 2023-09-30 2023-10-01 to 2023-12-31     144   0.5776    1.331
  13     2023-01-01 to 2023-12-31 2024-01-01 to 2024-03-31     143   1.2524    2.068
  14     2023-04-01 to 2024-03-31 2024-04-01 to 2024-06-30     145   0.1250    0.455
  15     2023-07-01 to 2024-06-30 2024-07-01 to 2024-09-30     141   0.1864    0.587
  16     2023-10-01 to 2024-09-30 2024-10-01 to 2024-12-31     128   0.8078    1.535
  17     2024-01-01 to 2024-12-31 2025-01-01 to 2025-03-31     131  -0.0102    0.157
  18     2024-04-01 to 2025-03-31 2025-04-01 to 2025-06-30     129  -0.1896   -0.329
  19     2024-07-01 to 2025-06-30 2025-07-01 to 2025-09-30     129  -0.0771   -0.038
  20     2024-10-01 to 2025-09-30 2025-10-01 to 2025-12-31     124  -0.2569   -0.606
============================================================


2026-04-16T05:42:37Z [INFO] Walk-forward: 20 windows, sma_crossover strategy, train=12m test=3m step=3m
2026-04-16T05:42:37Z [INFO]   Window 1/20: train=[2020-01-01, 2020-12-31] test=[2021-01-01, 2021-03-31]
2026-04-16T05:42:37Z [INFO] Starting backtest: strategy=sma_crossover, range=[2020-01-01, 2021-03-31], run_id=9d2c8087
2026-04-16T05:42:37Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T05:42:37Z [INFO]   Loaded 10925 bars: 2020-01-01 00:00:00 to 2021-03-31 23:00:00
2026-04-16T05:42:37Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T05:42:37Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T05:42:38Z [INFO] Metrics: return=2.7109 sharpe=2.240 maxDD=0.2733 trades=128 win_rate=0.37 PF=1.95
2026-04-16T05:42:38Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_9d2c8087-a445-46a3-b6a0-d4b123c471f0.csv (128 trades)
2026-04-16T05:42:38Z [INFO] Backtest complete: 128 trades, return=2.7109, sharpe=2.240, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_9d2c8087-a445-46a3-b6a0-d4b123c471f0.csv
2026-04-16T05:42:38Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_9d2c8087-a445-46a3-b6a0-d4b123c471f0.csv (20 trades)
2026-04-16T05:42:38Z [INFO] Metrics: return=2.7109 sharpe=2.461 maxDD=0.2000 trades=20 win_rate=0.40 PF=1.80
2026-04-16T05:42:38Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T05:42:38Z [INFO] Inserted run 9d2c8087-a445-46a3-b6a0-d4b123c471f0 (strategy: sma_crossover)
2026-04-16T05:42:38Z [INFO]     Window 1: 20 trades, return=2.7109, sharpe=2.461
2026-04-16T05:42:38Z [INFO]   Window 2/20: train=[2020-04-01, 2021-03-31] test=[2021-04-01, 2021-06-30]
2026-04-16T05:42:38Z [INFO] Starting backtest: strategy=sma_crossover, range=[2020-04-01, 2021-06-30], run_id=b6ef1f53
2026-04-16T05:42:38Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T05:42:38Z [INFO]   Loaded 10927 bars: 2020-04-01 00:00:00 to 2021-06-30 23:00:00
2026-04-16T05:42:38Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T05:42:38Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T05:42:39Z [INFO] Metrics: return=1.5435 sharpe=1.656 maxDD=0.3863 trades=123 win_rate=0.37 PF=1.38
2026-04-16T05:42:39Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_b6ef1f53-4dc2-4dab-8bef-3ee13c48de0d.csv (123 trades)
2026-04-16T05:42:39Z [INFO] Backtest complete: 123 trades, return=1.5435, sharpe=1.656, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_b6ef1f53-4dc2-4dab-8bef-3ee13c48de0d.csv
2026-04-16T05:42:39Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_b6ef1f53-4dc2-4dab-8bef-3ee13c48de0d.csv (24 trades)
2026-04-16T05:42:39Z [INFO] Metrics: return=1.5435 sharpe=-2.116 maxDD=0.3863 trades=24 win_rate=0.33 PF=0.43
2026-04-16T05:42:39Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T05:42:39Z [INFO] Inserted run b6ef1f53-4dc2-4dab-8bef-3ee13c48de0d (strategy: sma_crossover)
2026-04-16T05:42:39Z [INFO]     Window 2: 24 trades, return=1.5435, sharpe=-2.116
2026-04-16T05:42:39Z [INFO]   Window 3/20: train=[2020-07-01, 2021-06-30] test=[2021-07-01, 2021-09-30]
2026-04-16T05:42:39Z [INFO] Starting backtest: strategy=sma_crossover, range=[2020-07-01, 2021-09-30], run_id=8df34f98
2026-04-16T05:42:39Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T05:42:39Z [INFO]   Loaded 10950 bars: 2020-07-01 00:00:00 to 2021-09-30 23:00:00
2026-04-16T05:42:39Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T05:42:39Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T05:42:40Z [INFO] Metrics: return=0.9169 sharpe=1.230 maxDD=0.4207 trades=123 win_rate=0.35 PF=1.24
2026-04-16T05:42:40Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_8df34f98-d3b0-4baf-8df7-0ef951c098d8.csv (123 trades)
2026-04-16T05:42:40Z [INFO] Backtest complete: 123 trades, return=0.9169, sharpe=1.230, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_8df34f98-d3b0-4baf-8df7-0ef951c098d8.csv
2026-04-16T05:42:40Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_8df34f98-d3b0-4baf-8df7-0ef951c098d8.csv (25 trades)
2026-04-16T05:42:40Z [INFO] Metrics: return=0.9169 sharpe=0.082 maxDD=0.2053 trades=25 win_rate=0.32 PF=0.94
2026-04-16T05:42:40Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T05:42:40Z [INFO] Inserted run 8df34f98-d3b0-4baf-8df7-0ef951c098d8 (strategy: sma_crossover)
2026-04-16T05:42:40Z [INFO]     Window 3: 25 trades, return=0.9169, sharpe=0.082
2026-04-16T05:42:40Z [INFO]   Window 4/20: train=[2020-10-01, 2021-09-30] test=[2021-10-01, 2021-12-31]
2026-04-16T05:42:40Z [INFO] Starting backtest: strategy=sma_crossover, range=[2020-10-01, 2021-12-31], run_id=764eba1f
2026-04-16T05:42:40Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T05:42:40Z [INFO]   Loaded 10950 bars: 2020-10-01 00:00:00 to 2021-12-31 23:00:00
2026-04-16T05:42:40Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T05:42:40Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T05:42:42Z [INFO] Metrics: return=1.1132 sharpe=1.357 maxDD=0.4207 trades=121 win_rate=0.38 PF=1.25
2026-04-16T05:42:42Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_764eba1f-f5d2-4d23-abc5-fa897fa36643.csv (121 trades)
2026-04-16T05:42:42Z [INFO] Backtest complete: 121 trades, return=1.1132, sharpe=1.357, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_764eba1f-f5d2-4d23-abc5-fa897fa36643.csv
2026-04-16T05:42:42Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_764eba1f-f5d2-4d23-abc5-fa897fa36643.csv (26 trades)
2026-04-16T05:42:42Z [INFO] Metrics: return=1.1132 sharpe=0.278 maxDD=0.3179 trades=26 win_rate=0.31 PF=0.85
2026-04-16T05:42:42Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T05:42:42Z [INFO] Inserted run 764eba1f-f5d2-4d23-abc5-fa897fa36643 (strategy: sma_crossover)
2026-04-16T05:42:42Z [INFO]     Window 4: 26 trades, return=1.1132, sharpe=0.278
2026-04-16T05:42:42Z [INFO]   Window 5/20: train=[2021-01-01, 2021-12-31] test=[2022-01-01, 2022-03-31]
2026-04-16T05:42:42Z [INFO] Starting backtest: strategy=sma_crossover, range=[2021-01-01, 2022-03-31], run_id=f2d94cb7
2026-04-16T05:42:42Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T05:42:42Z [INFO]   Loaded 10907 bars: 2021-01-01 00:00:00 to 2022-03-31 23:00:00
2026-04-16T05:42:42Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T05:42:42Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T05:42:43Z [INFO] Metrics: return=0.0103 sharpe=0.282 maxDD=0.4583 trades=121 win_rate=0.36 PF=1.00
2026-04-16T05:42:43Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_f2d94cb7-56bf-40cf-b623-ecdd2d7bded0.csv (121 trades)
2026-04-16T05:42:43Z [INFO] Backtest complete: 121 trades, return=0.0103, sharpe=0.282, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_f2d94cb7-56bf-40cf-b623-ecdd2d7bded0.csv
2026-04-16T05:42:43Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_f2d94cb7-56bf-40cf-b623-ecdd2d7bded0.csv (23 trades)
2026-04-16T05:42:43Z [INFO] Metrics: return=0.0103 sharpe=0.292 maxDD=0.1793 trades=23 win_rate=0.43 PF=1.02
2026-04-16T05:42:43Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T05:42:43Z [INFO] Inserted run f2d94cb7-56bf-40cf-b623-ecdd2d7bded0 (strategy: sma_crossover)
2026-04-16T05:42:43Z [INFO]     Window 5: 23 trades, return=0.0103, sharpe=0.292
2026-04-16T05:42:43Z [INFO]   Window 6/20: train=[2021-04-01, 2022-03-31] test=[2022-04-01, 2022-06-30]
2026-04-16T05:42:43Z [INFO] Starting backtest: strategy=sma_crossover, range=[2021-04-01, 2022-06-30], run_id=d5437466
2026-04-16T05:42:43Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T05:42:43Z [INFO]   Loaded 10933 bars: 2021-04-01 00:00:00 to 2022-06-30 23:00:00
2026-04-16T05:42:43Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T05:42:43Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T05:42:45Z [INFO] Metrics: return=-0.5748 sharpe=-1.265 maxDD=0.6305 trades=127 win_rate=0.30 PF=0.67
2026-04-16T05:42:45Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_d5437466-eeb7-40dd-9dc9-411b1bc78811.csv (127 trades)
2026-04-16T05:42:45Z [INFO] Backtest complete: 127 trades, return=-0.5748, sharpe=-1.265, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_d5437466-eeb7-40dd-9dc9-411b1bc78811.csv
2026-04-16T05:42:45Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_d5437466-eeb7-40dd-9dc9-411b1bc78811.csv (27 trades)
2026-04-16T05:42:45Z [INFO] Metrics: return=-0.5748 sharpe=-5.491 maxDD=0.4366 trades=27 win_rate=0.11 PF=0.07
2026-04-16T05:42:45Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T05:42:45Z [INFO] Inserted run d5437466-eeb7-40dd-9dc9-411b1bc78811 (strategy: sma_crossover)
2026-04-16T05:42:45Z [INFO]     Window 6: 27 trades, return=-0.5748, sharpe=-5.491
2026-04-16T05:42:45Z [INFO]   Window 7/20: train=[2021-07-01, 2022-06-30] test=[2022-07-01, 2022-09-30]
2026-04-16T05:42:45Z [INFO] Starting backtest: strategy=sma_crossover, range=[2021-07-01, 2022-09-30], run_id=e18f6460
2026-04-16T05:42:45Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T05:42:45Z [INFO]   Loaded 10962 bars: 2021-07-01 00:00:00 to 2022-09-30 23:00:00
2026-04-16T05:42:45Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T05:42:45Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T05:42:46Z [INFO] Metrics: return=-0.3488 sharpe=-0.569 maxDD=0.6036 trades=128 win_rate=0.28 PF=0.82
2026-04-16T05:42:46Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_e18f6460-ddbe-44b1-a6e4-7ebb621fadc7.csv (128 trades)
2026-04-16T05:42:46Z [INFO] Backtest complete: 128 trades, return=-0.3488, sharpe=-0.569, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_e18f6460-ddbe-44b1-a6e4-7ebb621fadc7.csv
2026-04-16T05:42:46Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_e18f6460-ddbe-44b1-a6e4-7ebb621fadc7.csv (25 trades)
2026-04-16T05:42:46Z [INFO] Metrics: return=-0.3488 sharpe=1.095 maxDD=0.1858 trades=25 win_rate=0.24 PF=1.28
2026-04-16T05:42:46Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T05:42:46Z [INFO] Inserted run e18f6460-ddbe-44b1-a6e4-7ebb621fadc7 (strategy: sma_crossover)
2026-04-16T05:42:46Z [INFO]     Window 7: 25 trades, return=-0.3488, sharpe=1.095
2026-04-16T05:42:46Z [INFO]   Window 8/20: train=[2021-10-01, 2022-09-30] test=[2022-10-01, 2022-12-31]
2026-04-16T05:42:46Z [INFO] Starting backtest: strategy=sma_crossover, range=[2021-10-01, 2022-12-31], run_id=708abf83
2026-04-16T05:42:46Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T05:42:46Z [INFO]   Loaded 10968 bars: 2021-10-01 00:00:00 to 2022-12-31 23:00:00
2026-04-16T05:42:46Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T05:42:46Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T05:42:47Z [INFO] Metrics: return=-0.4424 sharpe=-1.004 maxDD=0.6036 trades=132 win_rate=0.26 PF=0.71
2026-04-16T05:42:47Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_708abf83-9e86-40f4-8e99-da94fd27bf78.csv (132 trades)
2026-04-16T05:42:47Z [INFO] Backtest complete: 132 trades, return=-0.4424, sharpe=-1.004, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_708abf83-9e86-40f4-8e99-da94fd27bf78.csv
2026-04-16T05:42:47Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_708abf83-9e86-40f4-8e99-da94fd27bf78.csv (29 trades)
2026-04-16T05:42:47Z [INFO] Metrics: return=-0.4424 sharpe=-1.228 maxDD=0.1080 trades=29 win_rate=0.24 PF=0.66
2026-04-16T05:42:47Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T05:42:47Z [INFO] Inserted run 708abf83-9e86-40f4-8e99-da94fd27bf78 (strategy: sma_crossover)
2026-04-16T05:42:47Z [INFO]     Window 8: 29 trades, return=-0.4424, sharpe=-1.228
2026-04-16T05:42:47Z [INFO]   Window 9/20: train=[2022-01-01, 2022-12-31] test=[2023-01-01, 2023-03-31]
2026-04-16T05:42:47Z [INFO] Starting backtest: strategy=sma_crossover, range=[2022-01-01, 2023-03-31], run_id=72ecc637
2026-04-16T05:42:47Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T05:42:47Z [INFO]   Loaded 10919 bars: 2022-01-01 00:00:00 to 2023-03-31 23:00:00
2026-04-16T05:42:47Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T05:42:47Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T05:42:49Z [INFO] Metrics: return=-0.0497 sharpe=0.094 maxDD=0.4418 trades=130 win_rate=0.28 PF=0.96
2026-04-16T05:42:49Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_72ecc637-828c-4617-a430-58748f7a885f.csv (130 trades)
2026-04-16T05:42:49Z [INFO] Backtest complete: 130 trades, return=-0.0497, sharpe=0.094, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_72ecc637-828c-4617-a430-58748f7a885f.csv
2026-04-16T05:42:49Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_72ecc637-828c-4617-a430-58748f7a885f.csv (25 trades)
2026-04-16T05:42:49Z [INFO] Metrics: return=-0.0497 sharpe=4.329 maxDD=0.1112 trades=25 win_rate=0.40 PF=2.60
2026-04-16T05:42:49Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T05:42:49Z [INFO] Inserted run 72ecc637-828c-4617-a430-58748f7a885f (strategy: sma_crossover)
2026-04-16T05:42:49Z [INFO]     Window 9: 25 trades, return=-0.0497, sharpe=4.329
2026-04-16T05:42:49Z [INFO]   Window 10/20: train=[2022-04-01, 2023-03-31] test=[2023-04-01, 2023-06-30]
2026-04-16T05:42:49Z [INFO] Starting backtest: strategy=sma_crossover, range=[2022-04-01, 2023-06-30], run_id=9b9a0898
2026-04-16T05:42:49Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T05:42:49Z [INFO]   Loaded 10943 bars: 2022-04-01 00:00:00 to 2023-06-30 23:00:00
2026-04-16T05:42:49Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T05:42:49Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T05:42:50Z [INFO] Metrics: return=-0.0808 sharpe=0.002 maxDD=0.4317 trades=136 win_rate=0.25 PF=0.94
2026-04-16T05:42:50Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_9b9a0898-5dc3-482b-93f5-b2319a19eb94.csv (136 trades)
2026-04-16T05:42:50Z [INFO] Backtest complete: 136 trades, return=-0.0808, sharpe=0.002, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_9b9a0898-5dc3-482b-93f5-b2319a19eb94.csv
2026-04-16T05:42:50Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_9b9a0898-5dc3-482b-93f5-b2319a19eb94.csv (29 trades)
2026-04-16T05:42:50Z [INFO] Metrics: return=-0.0808 sharpe=0.030 maxDD=0.1575 trades=29 win_rate=0.28 PF=0.98
2026-04-16T05:42:50Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T05:42:50Z [INFO] Inserted run 9b9a0898-5dc3-482b-93f5-b2319a19eb94 (strategy: sma_crossover)
2026-04-16T05:42:50Z [INFO]     Window 10: 29 trades, return=-0.0808, sharpe=0.030
2026-04-16T05:42:50Z [INFO]   Window 11/20: train=[2022-07-01, 2023-06-30] test=[2023-07-01, 2023-09-30]
2026-04-16T05:42:50Z [INFO] Starting backtest: strategy=sma_crossover, range=[2022-07-01, 2023-09-30], run_id=13fae1d2

## B. Fetch Latest Summary Row

The latest `walk_forward_summary` row is the parent for this acceptance run.

In [3]:
summary_df = read_runs_query("""
SELECT *
FROM runs
WHERE run_type = 'walk_forward_summary'
ORDER BY created_at_utc DESC
LIMIT 1
""")

display(summary_df.T)

assert len(summary_df) == 1, "Expected exactly one latest walk_forward_summary row"
summary = summary_df.iloc[0]
summary_run_id = summary["run_id"]
print("summary_run_id:", summary_run_id)

summary_checks = [
    check_row("summary row exists", len(summary_df) == 1),
    check_row("summary run_type", summary["run_type"] == "walk_forward_summary", summary["run_type"]),
    check_row("summary parent_run_id is NULL", pd.isna(summary["parent_run_id"]), summary["parent_run_id"]),
    check_row("summary strategy_name", summary["strategy_name"] == "sma_crossover", summary["strategy_name"]),
    check_row("summary fee_model", summary["fee_model"] == "effective_7bps_per_side", summary["fee_model"]),
]
display_check_table(summary_checks, "Summary row checks")
D11_ACCEPTANCE["summary_row"] = True

                                                                                                                     0
run_id                                                                            92eb97ae-08e6-482d-8c1d-85313ed258f3
run_type                                                                                          walk_forward_summary
parent_run_id                                                                                                     None
strategy_name                                                                                            sma_crossover
strategy_source                                                                                                 manual
git_commit                                                                                                     8411d22
config_hash                                                                                    sha256:57d14658de08d92d
data_snapshot_date                                                                                                None
feature_version                                                                                                   none
split_version                                                                                                       v1
train_start                                                                                       2020-01-01T00:00:00Z
train_end                                                                                         2025-09-30T23:00:00Z
validation_start                                                                                                  None
validation_end                                                                                                    None
test_start                                                                                        2021-01-01T00:00:00Z
test_end                                                                                          2025-12-31T23:00:00Z
effective_start                                                                                                   None
warmup_bars                                                                                                         50
initial_capital                                                                                                10000.0
final_capital                                                                                                     None
total_return                                                                                                  0.374825
sharpe_ratio                                                                                                 -0.178381
max_drawdown                                                                                                  0.436579
max_drawdown_duration_hours                                                                                     2145.0
total_trades                                                                                                       513
win_rate                                                                                                      0.323587
avg_trade_duration_hours                                                                                     43.012908
avg_trade_return                                                                                              0.000284
profit_factor                                                                                                  1.06946
fee_model                                                                                      effective_7bps_per_side
notes                        {"num_windows": 20, "train_months": 12, "test_months": 3, "step_months": 3, "params": {}}
review_status                                                                                                  pending
review_reason                                                                                                     None
created_at_utc                                                                                    2026-04-16T12:43:02Z

summary_run_id: 92eb97ae-08e6-482d-8c1d-85313ed258f3
Summary row checks

                           check status                   detail
0             summary row exists   PASS
1               summary run_type   PASS     walk_forward_summary
2  summary parent_run_id is NULL   PASS                      NaN
3          summary strategy_name   PASS            sma_crossover
4              summary fee_model   PASS  effective_7bps_per_side

## C. Fetch Window Rows

Each window row must have `run_type = walk_forward_window` and `parent_run_id = summary_run_id`.

In [4]:
windows_df = read_runs_query("""
SELECT *
FROM runs
WHERE run_type = 'walk_forward_window'
  AND parent_run_id = ?
ORDER BY test_start
""", params=(summary_run_id,))

window_display_cols = [
    "run_id",
    "parent_run_id",
    "train_start",
    "train_end",
    "test_start",
    "test_end",
    "initial_capital",
    "final_capital",
    "total_trades",
    "sharpe_ratio",
    "total_return",
    "max_drawdown",
]
display(windows_df[window_display_cols])

assert len(windows_df) > 0, "No walk_forward_window rows found"
D11_ACCEPTANCE["window_rows_loaded"] = True
print(f"Loaded {len(windows_df)} window rows for summary {summary_run_id}")

,run_id,parent_run_id,train_start,train_end,test_start,test_end,initial_capital,final_capital,total_trades,sharpe_ratio,total_return,max_drawdown
0,9d2c8087-a445-46a3-b6a0-d4b123c471f0,92eb97ae-08e6-482d-8c1d-85313ed258f3,2020-01-01T00:00:00Z,2020-12-31T23:00:00Z,2021-01-01T00:00:00Z,2021-03-31T23:00:00Z,10000.0,37109.271310,20,2.461450,2.710927,0.199996
1,b6ef1f53-4dc2-4dab-8bef-3ee13c48de0d,92eb97ae-08e6-482d-8c1d-85313ed258f3,2020-04-01T00:00:00Z,2021-03-31T23:00:00Z,2021-04-01T00:00:00Z,2021-06-30T23:00:00Z,10000.0,25435.072353,24,-2.115818,1.543507,0.386292
2,8df34f98-d3b0-4baf-8df7-0ef951c098d8,92eb97ae-08e6-482d-8c1d-85313ed258f3,2020-07-01T00:00:00Z,2021-06-30T23:00:00Z,2021-07-01T00:00:00Z,2021-09-30T23:00:00Z,10000.0,19168.502049,25,0.081637,0.916850,0.205315
3,764eba1f-f5d2-4d23-abc5-fa897fa36643,92eb97ae-08e6-482d-8c1d-85313ed258f3,2020-10-01T00:00:00Z,2021-09-30T23:00:00Z,2021-10-01T00:00:00Z,2021-12-31T23:00:00Z,10000.0,21132.322255,26,0.277892,1.113232,0.317930
4,f2d94cb7-56bf-40cf-b623-ecdd2d7bded0,92eb97ae-08e6-482d-8c1d-85313ed258f3,2021-01-01T00:00:00Z,2021-12-31T23:00:00Z,2022-01-01T00:00:00Z,2022-03-31T23:00:00Z,10000.0,10102.785476,23,0.291954,0.010279,0.179252
5,d5437466-eeb7-40dd-9dc9-411b1bc78811,92eb97ae-08e6-482d-8c1d-85313ed258f3,2021-04-01T00:00:00Z,2022-03-31T23:00:00Z,2022-04-01T00:00:00Z,2022-06-30T23:00:00Z,10000.0,4251.980238,27,-5.491045,-0.574802,0.436579
6,e18f6460-ddbe-44b1-a6e4-7ebb621fadc7,92eb97ae-08e6-482d-8c1d-85313ed258f3,2021-07-01T00:00:00Z,2022-06-30T23:00:00Z,2022-07-01T00:00:00Z,2022-09-30T23:00:00Z,10000.0,6512.450965,25,1.095467,-0.348755,0.185761
7,708abf83-9e86-40f4-8e99-da94fd27bf78,92eb97ae-08e6-482d-8c1d-85313ed258f3,2021-10-01T00:00:00Z,2022-09-30T23:00:00Z,2022-10-01T00:00:00Z,2022-12-31T23:00:00Z,10000.0,5575.784864,29,-1.227828,-0.442422,0.108024
8,72ecc637-828c-4617-a430-58748f7a885f,92eb97ae-08e6-482d-8c1d-85313ed258f3,2022-01-01T00:00:00Z,2022-12-31T23:00:00Z,2023-01-01T00:00:00Z,2023-03-31T23:00:00Z,10000.0,9502.994118,25,4.328595,-0.049701,0.111195
9,9b9a0898-5dc3-482b-93f5-b2319a19eb94,92eb97ae-08e6-482d-8c1d-85313ed258f3,2022-04-01T00:00:00Z,2023-03-31T23:00:00Z,2023-04-01T00:00:00Z,2023-06-30T23:00:00Z,10000.0,9191.967108,29,0.029617,-0.080803,0.157481
10,13fae1d2-f278-4e30-ad78-c6580c6a12a0,92eb97ae-08e6-482d-8c1d-85313ed258f3,2022-07-01T00:00:00Z,2023-06-30T23:00:00Z,2023-07-01T00:00:00Z,2023-09-30T23:00:00Z,10000.0,12827.471366,36,-3.908275,0.282747,0.215305
11,740b76e8-261c-408e-b8dc-c9ea8ebd03da,92eb97ae-08e6-482d-8c1d-85313ed258f3,2022-10-01T00:00:00Z,2023-09-30T23:00:00Z,2023-10-01T00:00:00Z,2023-12-31T23:00:00Z,10000.0,15776.141423,22,3.865061,0.577614,0.085186
12,b4337aa4-b1a8-4187-876a-efb904b06b1d,92eb97ae-08e6-482d-8c1d-85313ed258f3,2023-01-01T00:00:00Z,2023-12-31T23:00:00Z,2024-01-01T00:00:00Z,2024-03-31T23:00:00Z,10000.0,22524.019032,29,2.965527,1.252402,0.141760
13,04d23494-d9be-45d5-8672-1770920098dd,92eb97ae-08e6-482d-8c1d-85313ed258f3,2023-04-01T00:00:00Z,2024-03-31T23:00:00Z,2024-04-01T00:00:00Z,2024-06-30T23:00:00Z,10000.0,11249.954467,26,-3.280079,0.124995,0.295659
14,d2fa3b5f-308b-4d4e-b533-15400bfdd7fa,92eb97ae-08e6-482d-8c1d-85313ed258f3,2023-07-01T00:00:00Z,2024-06-30T23:00:00Z,2024-07-01T00:00:00Z,2024-09-30T23:00:00Z,10000.0,11864.089250,25,0.836323,0.186409,0.135949
15,98460b80-d937-45eb-a1df-f2e638d8c825,92eb97ae-08e6-482d-8c1d-85313ed258f3,2023-10-01T00:00:00Z,2024-09-30T23:00:00Z,2024-10-01T00:00:00Z,2024-12-31T23:00:00Z,10000.0,18078.212950,23,2.873971,0.807821,0.100984
16,e5dd30da-ca88-41ed-a7d7-f9ad7c1e35f7,92eb97ae-08e6-482d-8c1d-85313ed258f3,2024-01-01T00:00:00Z,2024-12-31T23:00:00Z,2025-01-01T00:00:00Z,2025-03-31T23:00:00Z,10000.0,9897.607860,25,-3.111834,-0.010239,0.336226
17,c2bdac07-c637-4416-a9fb-ab04e22f0d0a,92eb97ae-08e6-482d-8c1d-85313ed258f3,2024-04-01T00:00:00Z,2025-03-31T23:00:00Z,2025-04-01T00:00:00Z,2025-06-30T23:00:00Z,10000.0,8103.852223,28,0.501895,-0.189615,0.146384
18,9dae985c-6bdb-4f02-80ff-053bc835bf30,92eb97ae-08e6-482d-8c1d-85313ed258f3,2024-07-01T00:00:00Z,2025-06-30T23:00:00Z,2025-07-01T00:00:00Z,2025-09-30T23:00:00Z,10000.0,9229.217114,27,-2.010685,-0.077078,0.222958
19,14400054-5538-4680-9c5b-52f1e7b9c7d9,92eb97ae-08e6-482d-8c1d-85313ed258f3,2024-10-01T00:00:00Z,2025-09-30T23:00:00Z,2025-10-01T00:00:00Z,2025-12-31T23:00:00Z,10000.0,7431.300715,19,-2.031454,-0.256870,0.217169

Loaded 20 window rows for summary 92eb97ae-08e6-482d-8c1d-85313ed258f3

## D. Window Generation Matches `environments.yaml`

Compare registry rows against `generate_walk_forward_windows()` using the config values from `config/environments.yaml`.

In [5]:
from backtest.engine import generate_walk_forward_windows

env_config = yaml.safe_load(ENV_PATH.read_text())
wf_config = env_config["walk_forward"]
train_months = int(wf_config["train_window_months"])
test_months = int(wf_config["test_window_months"])
step_months = int(wf_config["step_months"])
overall_start = date.fromisoformat(env_config["splits"]["training"]["start"])
overall_end = date.fromisoformat(env_config["splits"]["test"]["end"])

expected_windows = generate_walk_forward_windows(
    overall_start=overall_start,
    overall_end=overall_end,
    train_months=train_months,
    test_months=test_months,
    step_months=step_months,
)

expected_windows_df = pd.DataFrame(
    expected_windows,
    columns=["expected_train_start", "expected_train_end", "expected_test_start", "expected_test_end"],
)
actual_windows_df = windows_df[["train_start", "train_end", "test_start", "test_end"]].copy()
for col in actual_windows_df.columns:
    actual_windows_df[col] = pd.to_datetime(actual_windows_df[col], utc=True).dt.date

comparison_df = pd.concat([expected_windows_df, actual_windows_df], axis=1)
display(comparison_df)

window_generation_checks = [
    check_row("window count matches generated tuples", len(windows_df) == len(expected_windows), f"actual={len(windows_df)}, expected={len(expected_windows)}"),
    check_row("train_start matches", actual_windows_df["train_start"].tolist() == expected_windows_df["expected_train_start"].tolist()),
    check_row("train_end matches", actual_windows_df["train_end"].tolist() == expected_windows_df["expected_train_end"].tolist()),
    check_row("test_start matches", actual_windows_df["test_start"].tolist() == expected_windows_df["expected_test_start"].tolist()),
    check_row("test_end matches", actual_windows_df["test_end"].tolist() == expected_windows_df["expected_test_end"].tolist()),
]
display_check_table(window_generation_checks, "Window generation checks")
D11_ACCEPTANCE["window_generation"] = True

   expected_train_start expected_train_end expected_test_start expected_test_end train_start   train_end  test_start    test_end
0            2020-01-01         2020-12-31          2021-01-01        2021-03-31  2020-01-01  2020-12-31  2021-01-01  2021-03-31
1            2020-04-01         2021-03-31          2021-04-01        2021-06-30  2020-04-01  2021-03-31  2021-04-01  2021-06-30
2            2020-07-01         2021-06-30          2021-07-01        2021-09-30  2020-07-01  2021-06-30  2021-07-01  2021-09-30
3            2020-10-01         2021-09-30          2021-10-01        2021-12-31  2020-10-01  2021-09-30  2021-10-01  2021-12-31
4            2021-01-01         2021-12-31          2022-01-01        2022-03-31  2021-01-01  2021-12-31  2022-01-01  2022-03-31
5            2021-04-01         2022-03-31          2022-04-01        2022-06-30  2021-04-01  2022-03-31  2022-04-01  2022-06-30
6            2021-07-01         2022-06-30          2022-07-01        2022-09-30  2021-07-01  2022-06-30  2022-07-01  2022-09-30
7            2021-10-01         2022-09-30          2022-10-01        2022-12-31  2021-10-01  2022-09-30  2022-10-01  2022-12-31
8            2022-01-01         2022-12-31          2023-01-01        2023-03-31  2022-01-01  2022-12-31  2023-01-01  2023-03-31
9            2022-04-01         2023-03-31          2023-04-01        2023-06-30  2022-04-01  2023-03-31  2023-04-01  2023-06-30
10           2022-07-01         2023-06-30          2023-07-01        2023-09-30  2022-07-01  2023-06-30  2023-07-01  2023-09-30
11           2022-10-01         2023-09-30          2023-10-01        2023-12-31  2022-10-01  2023-09-30  2023-10-01  2023-12-31
12           2023-01-01         2023-12-31          2024-01-01        2024-03-31  2023-01-01  2023-12-31  2024-01-01  2024-03-31
13           2023-04-01         2024-03-31          2024-04-01        2024-06-30  2023-04-01  2024-03-31  2024-04-01  2024-06-30
14           2023-07-01         2024-06-30          2024-07-01        2024-09-30  2023-07-01  2024-06-30  2024-07-01  2024-09-30
15           2023-10-01         2024-09-30          2024-10-01        2024-12-31  2023-10-01  2024-09-30  2024-10-01  2024-12-31
16           2024-01-01         2024-12-31          2025-01-01        2025-03-31  2024-01-01  2024-12-31  2025-01-01  2025-03-31
17           2024-04-01         2025-03-31          2025-04-01        2025-06-30  2024-04-01  2025-03-31  2025-04-01  2025-06-30
18           2024-07-01         2025-06-30          2025-07-01        2025-09-30  2024-07-01  2025-06-30  2025-07-01  2025-09-30
19           2024-10-01         2025-09-30          2025-10-01        2025-12-31  2024-10-01  2025-09-30  2025-10-01  2025-12-31

Window generation checks

                                   check status                  detail
0  window count matches generated tuples   PASS  actual=20, expected=20
1                    train_start matches   PASS
2                      train_end matches   PASS
3                     test_start matches   PASS
4                       test_end matches   PASS

## E. Four-Item Isolation Checklist

These are the core D11 isolation checks:

1. Every window has a distinct `run_id`.
2. Every window points to the same parent summary.
3. Every window resets `initial_capital` instead of inheriting previous `final_capital`.
4. Every window's trade artifact contains only trades inside its test period.

In [6]:
# Checklist 1: unique run_id
unique_run_id = windows_df["run_id"].nunique() == len(windows_df)

# Checklist 2: same parent summary
one_parent = windows_df["parent_run_id"].nunique() == 1
parent_matches = bool(windows_df["parent_run_id"].iloc[0] == summary_run_id)

# Checklist 3: capital reset
initial_capital_unique = windows_df["initial_capital"].nunique() == 1
expected_initial = float(windows_df["initial_capital"].iloc[0])
initial_is_baseline = np.isclose(expected_initial, 10_000.0, rtol=0, atol=1e-9)
prev_finals = windows_df["final_capital"].shift(1)
capital_leak_mask = np.isclose(windows_df["initial_capital"], prev_finals, rtol=0, atol=1e-9)
capital_leak_mask = pd.Series(capital_leak_mask, index=windows_df.index).fillna(False)
no_capital_inheritance = not bool(capital_leak_mask.any())

capital_table = windows_df[["run_id", "initial_capital", "final_capital"]].copy()
capital_table["prev_final_capital"] = prev_finals
capital_table["looks_like_inherited_capital"] = capital_leak_mask
display(capital_table)

isolation_checks = [
    check_row("each window has unique run_id", unique_run_id, f"unique={windows_df['run_id'].nunique()}, rows={len(windows_df)}"),
    check_row("all windows share one parent_run_id", one_parent, str(windows_df["parent_run_id"].unique())),
    check_row("parent_run_id matches summary_run_id", parent_matches, summary_run_id),
    check_row("initial_capital identical across windows", initial_capital_unique, str(windows_df["initial_capital"].unique())),
    check_row("initial_capital resets to 10000", initial_is_baseline, expected_initial),
    check_row("no later window initial equals prior final", no_capital_inheritance, capital_table.loc[capital_table["looks_like_inherited_capital"], ["run_id", "initial_capital", "prev_final_capital"]].to_dict(orient="records")),
]
display_check_table(isolation_checks, "Window identity/parent/capital isolation checks")
D11_ACCEPTANCE["identity_parent_capital_isolation"] = True

                                  run_id  initial_capital  final_capital  prev_final_capital  looks_like_inherited_capital
0   9d2c8087-a445-46a3-b6a0-d4b123c471f0          10000.0   37109.271310                 NaN                         False
1   b6ef1f53-4dc2-4dab-8bef-3ee13c48de0d          10000.0   25435.072353        37109.271310                         False
2   8df34f98-d3b0-4baf-8df7-0ef951c098d8          10000.0   19168.502049        25435.072353                         False
3   764eba1f-f5d2-4d23-abc5-fa897fa36643          10000.0   21132.322255        19168.502049                         False
4   f2d94cb7-56bf-40cf-b623-ecdd2d7bded0          10000.0   10102.785476        21132.322255                         False
5   d5437466-eeb7-40dd-9dc9-411b1bc78811          10000.0    4251.980238        10102.785476                         False
6   e18f6460-ddbe-44b1-a6e4-7ebb621fadc7          10000.0    6512.450965         4251.980238                         False
7   708abf83-9e86-40f4-8e99-da94fd27bf78          10000.0    5575.784864         6512.450965                         False
8   72ecc637-828c-4617-a430-58748f7a885f          10000.0    9502.994118         5575.784864                         False
9   9b9a0898-5dc3-482b-93f5-b2319a19eb94          10000.0    9191.967108         9502.994118                         False
10  13fae1d2-f278-4e30-ad78-c6580c6a12a0          10000.0   12827.471366         9191.967108                         False
11  740b76e8-261c-408e-b8dc-c9ea8ebd03da          10000.0   15776.141423        12827.471366                         False
12  b4337aa4-b1a8-4187-876a-efb904b06b1d          10000.0   22524.019032        15776.141423                         False
13  04d23494-d9be-45d5-8672-1770920098dd          10000.0   11249.954467        22524.019032                         False
14  d2fa3b5f-308b-4d4e-b533-15400bfdd7fa          10000.0   11864.089250        11249.954467                         False
15  98460b80-d937-45eb-a1df-f2e638d8c825          10000.0   18078.212950        11864.089250                         False
16  e5dd30da-ca88-41ed-a7d7-f9ad7c1e35f7          10000.0    9897.607860        18078.212950                         False
17  c2bdac07-c637-4416-a9fb-ab04e22f0d0a          10000.0    8103.852223         9897.607860                         False
18  9dae985c-6bdb-4f02-80ff-053bc835bf30          10000.0    9229.217114         8103.852223                         False
19  14400054-5538-4680-9c5b-52f1e7b9c7d9          10000.0    7431.300715         9229.217114                         False

Window identity/parent/capital isolation checks

                                        check status                                                                               detail
0               each window has unique run_id   PASS                                                                   unique=20, rows=20
1         all windows share one parent_run_id   PASS  <ArrowStringArray>\n['92eb97ae-08e6-482d-8c1d-85313ed258f3']\nLength: 1, dtype: str
2        parent_run_id matches summary_run_id   PASS                                                 92eb97ae-08e6-482d-8c1d-85313ed258f3
3    initial_capital identical across windows   PASS                                                                             [10000.]
4             initial_capital resets to 10000   PASS                                                                              10000.0
5  no later window initial equals prior final   PASS                                                                                   []

### E4. Trade Artifact Window Isolation

This is the strongest check for no trade/position leakage. For every window row, load `data/results/trades_{run_id}.csv` and verify all completed trade entry/exit times fall within that window's `test_start` to `test_end` range.

If this fails, D11 should not be signed off: it means the persisted artifact is not test-window isolated even if registry metrics are.

In [7]:
trade_artifact_rows = []
trade_leak_rows = []

for _, row in windows_df.iterrows():
    run_id = row["run_id"]
    trade_path = RESULTS_DIR / f"trades_{run_id}.csv"
    test_start = pd.Timestamp(row["test_start"], tz="UTC") if pd.Timestamp(row["test_start"]).tzinfo is None else pd.Timestamp(row["test_start"])
    test_end = pd.Timestamp(row["test_end"], tz="UTC") if pd.Timestamp(row["test_end"]).tzinfo is None else pd.Timestamp(row["test_end"])

    artifact = {
        "run_id": run_id,
        "trade_path": str(trade_path),
        "trade_csv_exists": trade_path.exists(),
        "registry_total_trades": int(row["total_trades"]),
        "csv_rows": None,
        "all_entries_in_test": None,
        "all_exits_in_test": None,
        "row_count_matches_registry": None,
    }

    if not trade_path.exists():
        trade_leak_rows.append({"run_id": run_id, "issue": "missing trade CSV", "detail": str(trade_path)})
        trade_artifact_rows.append(artifact)
        continue

    trades = pd.read_csv(
        trade_path,
        parse_dates=["entry_time_utc", "exit_time_utc", "entry_signal_time_utc", "exit_signal_time_utc"],
    )
    artifact["csv_rows"] = len(trades)
    artifact["row_count_matches_registry"] = len(trades) == int(row["total_trades"])

    if len(trades) == 0:
        artifact["all_entries_in_test"] = True
        artifact["all_exits_in_test"] = True
    else:
        entry_ok = (trades["entry_time_utc"] >= test_start) & (trades["entry_time_utc"] <= test_end)
        exit_ok = (trades["exit_time_utc"] >= test_start) & (trades["exit_time_utc"] <= test_end)
        artifact["all_entries_in_test"] = bool(entry_ok.all())
        artifact["all_exits_in_test"] = bool(exit_ok.all())

        leaked = trades[~(entry_ok & exit_ok)].copy()
        if len(leaked) > 0:
            leaked.insert(0, "run_id", run_id)
            leaked.insert(1, "test_start", test_start)
            leaked.insert(2, "test_end", test_end)
            trade_leak_rows.extend(leaked[[
                "run_id", "test_start", "test_end", "trade_id",
                "entry_signal_time_utc", "entry_time_utc",
                "exit_signal_time_utc", "exit_time_utc",
            ]].to_dict(orient="records"))

    trade_artifact_rows.append(artifact)

trade_artifact_df = pd.DataFrame(trade_artifact_rows)
display(trade_artifact_df)

if trade_leak_rows:
    leak_df = pd.DataFrame(trade_leak_rows)
    display(leak_df.head(30))
else:
    leak_df = pd.DataFrame()

trade_isolation_checks = [
    check_row("all per-window trade CSVs exist", bool(trade_artifact_df["trade_csv_exists"].all())),
    check_row("CSV row counts match registry total_trades", bool(trade_artifact_df["row_count_matches_registry"].all()), trade_artifact_df.loc[~trade_artifact_df["row_count_matches_registry"].fillna(False)].to_dict(orient="records")),
    check_row("all trade entries are inside their test window", bool(trade_artifact_df["all_entries_in_test"].all()), f"leaked_rows={len(leak_df)}"),
    check_row("all trade exits are inside their test window", bool(trade_artifact_df["all_exits_in_test"].all()), f"leaked_rows={len(leak_df)}"),
]
display_check_table(trade_isolation_checks, "Trade artifact isolation checks")
D11_ACCEPTANCE["trade_artifact_isolation"] = True

,run_id,trade_path,trade_csv_exists,registry_total_trades,csv_rows,all_entries_in_test,all_exits_in_test,row_count_matches_registry
0,9d2c8087-a445-46a3-b6a0-d4b123c471f0,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_9d2c8087-a445-46a3-b6a0-d4b123c471f0.csv,True,20,20,True,True,True
1,b6ef1f53-4dc2-4dab-8bef-3ee13c48de0d,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_b6ef1f53-4dc2-4dab-8bef-3ee13c48de0d.csv,True,24,24,True,True,True
2,8df34f98-d3b0-4baf-8df7-0ef951c098d8,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_8df34f98-d3b0-4baf-8df7-0ef951c098d8.csv,True,25,25,True,True,True
3,764eba1f-f5d2-4d23-abc5-fa897fa36643,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_764eba1f-f5d2-4d23-abc5-fa897fa36643.csv,True,26,26,True,True,True
4,f2d94cb7-56bf-40cf-b623-ecdd2d7bded0,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_f2d94cb7-56bf-40cf-b623-ecdd2d7bded0.csv,True,23,23,True,True,True
5,d5437466-eeb7-40dd-9dc9-411b1bc78811,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_d5437466-eeb7-40dd-9dc9-411b1bc78811.csv,True,27,27,True,True,True
6,e18f6460-ddbe-44b1-a6e4-7ebb621fadc7,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_e18f6460-ddbe-44b1-a6e4-7ebb621fadc7.csv,True,25,25,True,True,True
7,708abf83-9e86-40f4-8e99-da94fd27bf78,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_708abf83-9e86-40f4-8e99-da94fd27bf78.csv,True,29,29,True,True,True
8,72ecc637-828c-4617-a430-58748f7a885f,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_72ecc637-828c-4617-a430-58748f7a885f.csv,True,25,25,True,True,True
9,9b9a0898-5dc3-482b-93f5-b2319a19eb94,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_9b9a0898-5dc3-482b-93f5-b2319a19eb94.csv,True,29,29,True,True,True
10,13fae1d2-f278-4e30-ad78-c6580c6a12a0,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_13fae1d2-f278-4e30-ad78-c6580c6a12a0.csv,True,36,36,True,True,True
11,740b76e8-261c-408e-b8dc-c9ea8ebd03da,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_740b76e8-261c-408e-b8dc-c9ea8ebd03da.csv,True,22,22,True,True,True
12,b4337aa4-b1a8-4187-876a-efb904b06b1d,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_b4337aa4-b1a8-4187-876a-efb904b06b1d.csv,True,29,29,True,True,True
13,04d23494-d9be-45d5-8672-1770920098dd,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_04d23494-d9be-45d5-8672-1770920098dd.csv,True,26,26,True,True,True
14,d2fa3b5f-308b-4d4e-b533-15400bfdd7fa,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_d2fa3b5f-308b-4d4e-b533-15400bfdd7fa.csv,True,25,25,True,True,True
15,98460b80-d937-45eb-a1df-f2e638d8c825,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_98460b80-d937-45eb-a1df-f2e638d8c825.csv,True,23,23,True,True,True
16,e5dd30da-ca88-41ed-a7d7-f9ad7c1e35f7,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_e5dd30da-ca88-41ed-a7d7-f9ad7c1e35f7.csv,True,25,25,True,True,True
17,c2bdac07-c637-4416-a9fb-ab04e22f0d0a,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_c2bdac07-c637-4416-a9fb-ab04e22f0d0a.csv,True,28,28,True,True,True
18,9dae985c-6bdb-4f02-80ff-053bc835bf30,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_9dae985c-6bdb-4f02-80ff-053bc835bf30.csv,True,27,27,True,True,True
19,14400054-5538-4680-9c5b-52f1e7b9c7d9,/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_14400054-5538-4680-9c5b-52f1e7b9c7d9.csv,True,19,19,True,True,True

Trade artifact isolation checks

                                            check status         detail
0                 all per-window trade CSVs exist   PASS
1      CSV row counts match registry total_trades   PASS             []
2  all trade entries are inside their test window   PASS  leaked_rows=0
3    all trade exits are inside their test window   PASS  leaked_rows=0

## F. Summary Aggregation Consistency

The summary row must be mechanically reproducible from the window rows:

- mean Sharpe
- mean return
- summed trades
- worst drawdown
- max drawdown duration
- notes JSON with `num_windows` and config values

In [8]:
notes = json.loads(summary["notes"]) if isinstance(summary["notes"], str) and summary["notes"] else {}
print("Summary notes:")
display(pd.DataFrame([notes]).T.rename(columns={0: "value"}))

calc_mean_sharpe = float(windows_df["sharpe_ratio"].mean())
calc_mean_return = float(windows_df["total_return"].mean())
calc_total_trades = int(windows_df["total_trades"].sum())
calc_worst_drawdown = float(windows_df["max_drawdown"].max())
calc_max_dd_duration = float(windows_df["max_drawdown_duration_hours"].max())
calc_num_windows = len(windows_df)

summary_calc_df = pd.DataFrame([
    {"metric": "mean_sharpe", "calculated": calc_mean_sharpe, "summary_row": summary["sharpe_ratio"]},
    {"metric": "mean_return", "calculated": calc_mean_return, "summary_row": summary["total_return"]},
    {"metric": "total_trades", "calculated": calc_total_trades, "summary_row": summary["total_trades"]},
    {"metric": "worst_drawdown", "calculated": calc_worst_drawdown, "summary_row": summary["max_drawdown"]},
    {"metric": "max_drawdown_duration", "calculated": calc_max_dd_duration, "summary_row": summary["max_drawdown_duration_hours"]},
    {"metric": "num_windows", "calculated": calc_num_windows, "summary_row": notes.get("num_windows")},
])
display(summary_calc_df)

summary_agg_checks = [
    check_row("summary sharpe is mean window sharpe", np.isclose(summary["sharpe_ratio"], calc_mean_sharpe, rtol=1e-10, atol=1e-10)),
    check_row("summary return is mean window return", np.isclose(summary["total_return"], calc_mean_return, rtol=1e-10, atol=1e-10)),
    check_row("summary total_trades is sum windows", int(summary["total_trades"]) == calc_total_trades),
    check_row("summary max_drawdown is worst window drawdown", np.isclose(summary["max_drawdown"], calc_worst_drawdown, rtol=1e-10, atol=1e-10)),
    check_row("summary max drawdown duration is max window duration", np.isclose(summary["max_drawdown_duration_hours"], calc_max_dd_duration, rtol=1e-10, atol=1e-10)),
    check_row("notes num_windows matches", notes.get("num_windows") == calc_num_windows, notes.get("num_windows")),
    check_row("notes train_months matches config", notes.get("train_months") == train_months, notes.get("train_months")),
    check_row("notes test_months matches config", notes.get("test_months") == test_months, notes.get("test_months")),
    check_row("notes step_months matches config", notes.get("step_months") == step_months, notes.get("step_months")),
]
display_check_table(summary_agg_checks, "Summary aggregation checks")
D11_ACCEPTANCE["summary_aggregation"] = True

Summary notes:

             value
num_windows     20
train_months    12
test_months      3
step_months      3
params          {}

                  metric   calculated  summary_row
0            mean_sharpe    -0.178381    -0.178381
1            mean_return     0.374825     0.374825
2           total_trades   513.000000   513.000000
3         worst_drawdown     0.436579     0.436579
4  max_drawdown_duration  2145.000000  2145.000000
5            num_windows    20.000000    20.000000

Summary aggregation checks

                                                  check status detail
0                  summary sharpe is mean window sharpe   PASS
1                  summary return is mean window return   PASS
2                   summary total_trades is sum windows   PASS
3         summary max_drawdown is worst window drawdown   PASS
4  summary max drawdown duration is max window duration   PASS
5                             notes num_windows matches   PASS     20
6                     notes train_months matches config   PASS     12
7                      notes test_months matches config   PASS      3
8                      notes step_months matches config   PASS      3

## G. Single-Run Backward Compatibility

D11 touched registry writing and engine orchestration, so single-run mode must still work unchanged.

In [11]:
from backtest.engine import run_backtest
from strategies.baseline.sma_crossover import SMACrossover

single_result = run_backtest(
    strategy_cls=SMACrossover,
    start_date=datetime(2024, 1, 1, tzinfo=timezone.utc),
    end_date=datetime(2024, 6, 30, 23, tzinfo=timezone.utc),
    parquet_path=PARQUET_PATH,
    cash=10_000.0,
    write_registry=True,
)

single_df = read_runs_query("""
SELECT *
FROM runs
WHERE run_id = ?
""", params=(single_result.run_id,))
assert len(single_df) == 1, "Single-run registry row missing"
single_row = single_df.iloc[0]

display(single_df[[
    "run_id", "run_type", "parent_run_id", "strategy_name",
    "test_start", "test_end", "initial_capital", "final_capital",
    "total_trades", "sharpe_ratio", "total_return"
]])

single_trade_csv = RESULTS_DIR / f"trades_{single_result.run_id}.csv"
single_trades_df = pd.read_csv(single_trade_csv) if single_trade_csv.exists() else pd.DataFrame()

single_artifact_summary = pd.DataFrame([
    {"source": "result.trades", "trade_rows": len(single_result.trades)},
    {"source": "registry total_trades", "trade_rows": int(single_row["total_trades"])},
    {"source": "trade CSV rows", "trade_rows": len(single_trades_df)},
])
display(single_artifact_summary)

single_checks = [
    check_row("single run_type remains single_run", single_row["run_type"] == "single_run", single_row["run_type"]),
    check_row("single parent_run_id is NULL", pd.isna(single_row["parent_run_id"]), single_row["parent_run_id"]),
    check_row("single registry strategy is sma_crossover", single_row["strategy_name"] == "sma_crossover", single_row["strategy_name"]),
    check_row("single trade CSV exists", single_trade_csv.exists(), str(single_trade_csv)),
    check_row("single result has trades", single_result.metrics["total_trades"] > 0, single_result.metrics["total_trades"]),
    check_row(
        "single trade CSV row count equals result.trades",
        len(single_trades_df) == len(single_result.trades),
        f"csv_rows={len(single_trades_df)}, result_trades={len(single_result.trades)}",
    ),
    check_row(
        "single trade CSV row count equals registry total_trades",
        len(single_trades_df) == int(single_row["total_trades"]),
        f"csv_rows={len(single_trades_df)}, registry_total_trades={single_row['total_trades']}",
    ),
]
display_check_table(single_checks, "Single-run backward compatibility checks")
D11_ACCEPTANCE["single_run_backward_compatibility"] = True

2026-04-16T05:48:49Z [INFO] Starting backtest: strategy=sma_crossover, range=[2024-01-01, 2024-06-30], run_id=89732640
2026-04-16T05:48:49Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T05:48:49Z [INFO]   Loaded 4368 bars: 2024-01-01 00:00:00 to 2024-06-30 23:00:00
2026-04-16T05:48:49Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T05:48:49Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T05:48:50Z [INFO] Metrics: return=-0.0067 sharpe=0.141 maxDD=0.3178 trades=56 win_rate=0.38 PF=0.96
2026-04-16T05:48:50Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_89732640-5c6e-4671-8e42-df806119910a.csv (56 trades)
2026-04-16T05:48:50Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T05:48:50Z [INFO] Inserted run 89732640-5c6e-4671-8e42-df806119910a (strategy: sma_crossover)
2026-04-16T05:48:50Z [INFO] Backtest complete: 56 trades, return=-0.0067, sharpe=0.141, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_89732640-5c6e-4671-8e42-df806119910a.csv

                                 run_id    run_type parent_run_id  strategy_name            test_start              test_end  initial_capital  final_capital  total_trades  sharpe_ratio  total_return
0  89732640-5c6e-4671-8e42-df806119910a  single_run          None  sma_crossover  2024-01-01T00:00:00Z  2024-06-30T23:00:00Z          10000.0    9932.736819            56      0.141497     -0.006726

                  source  trade_rows
0          result.trades          56
1  registry total_trades          56
2         trade CSV rows          56

Single-run backward compatibility checks

                                                     check status                                                                                                              detail
0                       single run_type remains single_run   PASS                                                                                                          single_run
1                             single parent_run_id is NULL   PASS                                                                                                                None
2                single registry strategy is sma_crossover   PASS                                                                                                       sma_crossover
3                                  single trade CSV exists   PASS  /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_89732640-5c6e-4671-8e42-df806119910a.csv
4                                 single result has trades   PASS                                                                                                                  56
5          single trade CSV row count equals result.trades   PASS                                                                                       csv_rows=56, result_trades=56
6  single trade CSV row count equals registry total_trades   PASS                                                                               csv_rows=56, registry_total_trades=56

## H. D11 Final Acceptance Summary

In [10]:
d11_rows = [
    {"criterion": "walk-forward CLI completed", "status": pass_fail(D11_ACCEPTANCE.get("walk_forward_cli_run")), "evidence": "python -m backtest.engine --strategy sma_crossover --mode walk-forward"},
    {"criterion": "summary row exists", "status": pass_fail(D11_ACCEPTANCE.get("summary_row")), "evidence": "latest walk_forward_summary row fetched"},
    {"criterion": "window rows loaded", "status": pass_fail(D11_ACCEPTANCE.get("window_rows_loaded")), "evidence": "walk_forward_window rows with parent_run_id"},
    {"criterion": "window tuples match environments.yaml", "status": pass_fail(D11_ACCEPTANCE.get("window_generation")), "evidence": "registry dates match generate_walk_forward_windows()"},
    {"criterion": "run_id / parent / capital isolation", "status": pass_fail(D11_ACCEPTANCE.get("identity_parent_capital_isolation")), "evidence": "unique run_id, common summary parent, capital reset"},
    {"criterion": "trade artifact isolation", "status": pass_fail(D11_ACCEPTANCE.get("trade_artifact_isolation")), "evidence": "per-window trade CSV rows constrained to test windows"},
    {"criterion": "summary aggregation", "status": pass_fail(D11_ACCEPTANCE.get("summary_aggregation")), "evidence": "summary metrics recomputed from window rows"},
    {"criterion": "single-run backward compatibility", "status": pass_fail(D11_ACCEPTANCE.get("single_run_backward_compatibility")), "evidence": "single_run registry row and trade CSV still work"},
]

d11_summary_df = pd.DataFrame(d11_rows)
display(d11_summary_df)

failed = d11_summary_df[d11_summary_df["status"] != "PASS"]
assert failed.empty, failed

print("D11 WALK-FORWARD ACCEPTANCE PASS")
print("summary_run_id:", summary_run_id)
print("windows:", len(windows_df))

                               criterion status                                                                evidence
0             walk-forward CLI completed   PASS  python -m backtest.engine --strategy sma_crossover --mode walk-forward
1                     summary row exists   PASS                                 latest walk_forward_summary row fetched
2                     window rows loaded   PASS                             walk_forward_window rows with parent_run_id
3  window tuples match environments.yaml   PASS                    registry dates match generate_walk_forward_windows()
4    run_id / parent / capital isolation   PASS                     unique run_id, common summary parent, capital reset
5               trade artifact isolation   PASS                   per-window trade CSV rows constrained to test windows
6                    summary aggregation   PASS                             summary metrics recomputed from window rows
7      single-run backward compatibility   PASS                        single_run registry row and trade CSV still work

D11 WALK-FORWARD ACCEPTANCE PASS
summary_run_id: 92eb97ae-08e6-482d-8c1d-85313ed258f3
windows: 20

## I. D12 Post-Hoc DSR Heuristic Acceptance

D12 is accepted as a heuristic multiple-testing screen, not as a production-grade or formal Deflated Sharpe Ratio certification. These cells verify formula math, decision logic, real registry query filters, and report language.

In [16]:
from math import isclose, log, sqrt

from backtest.evaluate_dsr import (
    compute_expected_max_sharpe,
    evaluate_trials,
    query_sharpe_ratios,
)

D12_SPLIT_VERSION = "v1"
D12_DEFAULT_RUN_TYPE = "walk_forward_summary"
D12_ACCEPTANCE = {}

## J. Threshold Math

Checks the expected-max-Sharpe heuristic formula directly: `sqrt(2 * ln(N))`, with `N <= 1` returning `0`.

In [17]:
threshold_ns = [0, 1, 2, 5, 20, 100]
threshold_rows = []

for n in threshold_ns:
    actual = compute_expected_max_sharpe(n)
    expected = 0.0 if n <= 1 else sqrt(2 * log(n))
    threshold_rows.append({
        "N": n,
        "actual_threshold": actual,
        "expected_threshold": expected,
        "matches_formula": isclose(actual, expected, rel_tol=0, abs_tol=1e-12),
    })

threshold_df = pd.DataFrame(threshold_rows)
display(threshold_df)

positive_thresholds = threshold_df[threshold_df["N"] >= 1]["actual_threshold"].to_numpy()
threshold_checks = [
    check_row("N <= 1 returns zero", (threshold_df.loc[threshold_df["N"] <= 1, "actual_threshold"] == 0.0).all()),
    check_row("threshold equals sqrt(2 * ln(N))", threshold_df["matches_formula"].all()),
    check_row("threshold is monotonic non-decreasing", np.all(np.diff(positive_thresholds) >= 0)),
]
display_check_table(threshold_checks, "D12 threshold math checks")
D12_ACCEPTANCE["threshold_math"] = True

     N  actual_threshold  expected_threshold  matches_formula
0    0          0.000000            0.000000             True
1    1          0.000000            0.000000             True
2    2          1.177410            1.177410             True
3    5          1.794123            1.794123             True
4   20          2.447747            2.447747             True
5  100          3.034854            3.034854             True

D12 threshold math checks

                                   check status detail
0                    N <= 1 returns zero   PASS
1       threshold equals sqrt(2 * ln(N))   PASS
2  threshold is monotonic non-decreasing   PASS

## K. Decision Logic

Uses synthetic Sharpe trials so the acceptance boundary is visible: only `best_sharpe > threshold` survives; equality does not survive; empty input must not crash.

In [18]:
equal_threshold = compute_expected_max_sharpe(5)
decision_cases = [
    {
        "name": "N=1 positive Sharpe survives",
        "data": {"a": 0.5},
        "expected_survives": True,
    },
    {
        "name": "N=20 best=0.5 fails",
        "data": {f"s{i}": (0.5 if i == 0 else 0.1) for i in range(20)},
        "expected_survives": False,
    },
    {
        "name": "N=5 best=3.0 survives",
        "data": {"a": 3.0, "b": 0.2, "c": -0.1, "d": 0.5, "e": 0.3},
        "expected_survives": True,
    },
    {
        "name": "N=5 best equals threshold fails",
        "data": {"a": equal_threshold, "b": 0.2, "c": -0.1, "d": 0.5, "e": 0.3},
        "expected_survives": False,
    },
    {
        "name": "empty input does not crash",
        "data": {},
        "expected_survives": False,
    },
]

decision_rows = []
for case in decision_cases:
    result = evaluate_trials(case["data"])
    decision_rows.append({
        "case": case["name"],
        "N": result["n_trials"],
        "best_sharpe": result["best_sharpe"],
        "threshold": result["threshold"],
        "expected_survives": case["expected_survives"],
        "actual_survives": result["survives"],
        "pass": result["survives"] == case["expected_survives"],
        "rankings": result["rankings"],
    })

decision_df = pd.DataFrame(decision_rows)
display(decision_df)

decision_checks = [
    check_row("synthetic decision cases match expected boundary", decision_df["pass"].all(), decision_df.loc[~decision_df["pass"], ["case", "rankings"]].to_dict(orient="records")),
]
display_check_table(decision_checks, "D12 decision logic checks")
D12_ACCEPTANCE["decision_logic"] = True

,case,N,best_sharpe,threshold,expected_survives,actual_survives,pass,rankings
0,N=1 positive Sharpe survives,1,0.500000,0.000000,True,True,True,"[{'strategy': 'a', 'sharpe': 0.5}]"
1,N=20 best=0.5 fails,20,0.500000,2.447747,False,False,True,"[{'strategy': 's0', 'sharpe': 0.5}, {'strategy': 's1', 'sharpe': 0.1}, {'strategy': 's2', 'sharpe': 0.1}, {'strategy': 's3', 'sharpe': 0.1}, {'strategy': 's..."
2,N=5 best=3.0 survives,5,3.000000,1.794123,True,True,True,"[{'strategy': 'a', 'sharpe': 3.0}, {'strategy': 'd', 'sharpe': 0.5}, {'strategy': 'e', 'sharpe': 0.3}, {'strategy': 'b', 'sharpe': 0.2}, {'strategy': 'c', '..."
3,N=5 best equals threshold fails,5,1.794123,1.794123,False,False,True,"[{'strategy': 'a', 'sharpe': 1.7941225779941015}, {'strategy': 'd', 'sharpe': 0.5}, {'strategy': 'e', 'sharpe': 0.3}, {'strategy': 'b', 'sharpe': 0.2}, {'st..."
4,empty input does not crash,0,NaN,0.000000,False,False,True,[]

D12 decision logic checks

                                              check status detail
0  synthetic decision cases match expected boundary   PASS     []

## L. Registry Query Filters

Queries real `experiments.db` rows and cross-checks `query_sharpe_ratios()` against direct SQLite counts. This validates split, run type, strategy, and NULL-Sharpe exclusion semantics.

In [19]:
rows_default = query_sharpe_ratios(split_version=D12_SPLIT_VERSION)
rows_single = query_sharpe_ratios(split_version=D12_SPLIT_VERSION, run_type="single_run")
rows_sma = query_sharpe_ratios(split_version=D12_SPLIT_VERSION, strategy_name="sma_crossover")

with sqlite3.connect(DB_PATH) as conn:
    db_default = pd.read_sql_query("""
        SELECT run_id, strategy_name, run_type, split_version, sharpe_ratio
        FROM runs
        WHERE split_version = ?
          AND run_type = ?
          AND sharpe_ratio IS NOT NULL
        ORDER BY sharpe_ratio DESC
    """, conn, params=(D12_SPLIT_VERSION, D12_DEFAULT_RUN_TYPE))
    db_single = pd.read_sql_query("""
        SELECT run_id, strategy_name, run_type, split_version, sharpe_ratio
        FROM runs
        WHERE split_version = ?
          AND run_type = 'single_run'
          AND sharpe_ratio IS NOT NULL
        ORDER BY sharpe_ratio DESC
    """, conn, params=(D12_SPLIT_VERSION,))
    db_sma = pd.read_sql_query("""
        SELECT run_id, strategy_name, run_type, split_version, sharpe_ratio
        FROM runs
        WHERE split_version = ?
          AND run_type = ?
          AND strategy_name = 'sma_crossover'
          AND sharpe_ratio IS NOT NULL
        ORDER BY sharpe_ratio DESC
    """, conn, params=(D12_SPLIT_VERSION, D12_DEFAULT_RUN_TYPE))
    db_all_split = pd.read_sql_query("""
        SELECT run_id, strategy_name, run_type, split_version, sharpe_ratio
        FROM runs
        WHERE split_version = ?
        ORDER BY created_at_utc
    """, conn, params=(D12_SPLIT_VERSION,))

query_summary = pd.DataFrame([
    {"query": "default walk_forward_summary", "query_rows": len(rows_default), "db_non_null_rows": len(db_default)},
    {"query": "single_run", "query_rows": len(rows_single), "db_non_null_rows": len(db_single)},
    {"query": "sma_crossover walk_forward_summary", "query_rows": len(rows_sma), "db_non_null_rows": len(db_sma)},
])
display(query_summary)
display(db_all_split.head())
print("NULL Sharpe rows in split:", int(db_all_split["sharpe_ratio"].isna().sum()))
print("First query rows:", list(rows_default.items())[:5] if rows_default else "no rows")

query_checks = [
    check_row("default query returns real registry data", len(rows_default) > 0, f"split_version={D12_SPLIT_VERSION}, run_type={D12_DEFAULT_RUN_TYPE}"),
    check_row("split_version + default run_type count matches DB", len(rows_default) == len(db_default), query_summary.to_dict(orient="records")),
    check_row("run_type filter count matches DB", len(rows_single) == len(db_single), query_summary.to_dict(orient="records")),
    check_row("strategy_name filter count matches DB", len(rows_sma) == len(db_sma), query_summary.to_dict(orient="records")),
    check_row("query excludes NULL Sharpe", all(pd.notna(value) for value in [*rows_default.values(), *rows_single.values(), *rows_sma.values()])),
]
display_check_table(query_checks, "D12 registry query checks")
D12_ACCEPTANCE["registry_query_filters"] = True
D12_ACCEPTANCE["null_sharpe_exclusion"] = True

2026-04-16T06:08:37Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:08:37Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:08:37Z [INFO] Ensured 'runs' table exists with Phase 1A schema

                                query  query_rows  db_non_null_rows
0        default walk_forward_summary           2                 2
1                          single_run           9                 9
2  sma_crossover walk_forward_summary           2                 2

                                 run_id  strategy_name    run_type split_version  sharpe_ratio
0  6445c6a0-0b73-49ce-a517-fcd2ed045987  sma_crossover  single_run            v1      0.000000
1  7112415b-9c0b-47c1-815c-ce45004e8154  sma_crossover  single_run            v1      0.000000
2  14af73e6-6033-4fd8-8f50-25d0d5c0bcf5  sma_crossover  single_run            v1      1.046638
3  29d531c0-a7e3-40fe-bf68-ad245ba8e98b  sma_crossover  single_run            v1      1.046638
4  a45204b5-0c9b-4f5f-9bd1-61662cf671e1  sma_crossover  single_run            v1      1.046638

NULL Sharpe rows in split: 0
First query rows: [('sma_crossover (04d89e60)', -0.17838148214377175), ('sma_crossover (92eb97ae)', -0.17838148214377175)]
D12 registry query checks

,check,status,detail
0,default query returns real registry data,PASS,"split_version=v1, run_type=walk_forward_summary"
1,split_version + default run_type count matches DB,PASS,"[{'query': 'default walk_forward_summary', 'query_rows': 2, 'db_non_null_rows': 2}, {'query': 'single_run', 'query_rows': 9, 'db_non_null_rows': 9}, {'query..."
2,run_type filter count matches DB,PASS,"[{'query': 'default walk_forward_summary', 'query_rows': 2, 'db_non_null_rows': 2}, {'query': 'single_run', 'query_rows': 9, 'db_non_null_rows': 9}, {'query..."
3,strategy_name filter count matches DB,PASS,"[{'query': 'default walk_forward_summary', 'query_rows': 2, 'db_non_null_rows': 2}, {'query': 'single_run', 'query_rows': 9, 'db_non_null_rows': 9}, {'query..."
4,query excludes NULL Sharpe,PASS,

## M. CLI Report Semantics

Runs the real CLI and keeps the text output visible in the notebook. The key acceptance point is that the report labels itself as an approximate / heuristic screen rather than a formal DSR certification.

In [20]:
def run_dsr_cli(*args):
    cmd = [sys.executable, "-m", "backtest.evaluate_dsr", *args]
    completed = subprocess.run(cmd, cwd=PROJECT_ROOT, capture_output=True, text=True)
    output = (completed.stdout or "") + ("\n" + completed.stderr if completed.stderr else "")
    print("$", " ".join(cmd))
    print(output)
    assert completed.returncode == 0, f"DSR CLI failed with exit code {completed.returncode}"
    return output

cli_outputs = {
    "default_walk_forward_summary": run_dsr_cli("--split-version", D12_SPLIT_VERSION),
    "single_run": run_dsr_cli("--split-version", D12_SPLIT_VERSION, "--run-type", "single_run"),
    "sma_crossover": run_dsr_cli("--split-version", D12_SPLIT_VERSION, "--strategy", "sma_crossover"),
}

combined_output = "\n".join(cli_outputs.values()).lower()
semantic_checks = [
    check_row("report includes number of trials", "trials" in combined_output),
    check_row("report includes best/worst/mean Sharpe", all(term in combined_output for term in ["best sharpe", "worst sharpe", "mean sharpe"])),
    check_row("report includes threshold", "threshold" in combined_output),
    check_row("report includes survive/not-survive decision", "surviv" in combined_output),
    check_row("report includes strategy ranking", "rank" in combined_output),
    check_row("report explicitly says heuristic and approximate", ("heuristic" in combined_output) and ("approximate" in combined_output)),
    check_row("report says it is not full DSR", ("not the" in combined_output) and ("deflated sharpe ratio" in combined_output)),
]
display_check_table(semantic_checks, "D12 CLI report semantics checks")
D12_ACCEPTANCE["cli_report_output"] = True
D12_ACCEPTANCE["explicit_heuristic_disclaimer"] = True

$ /Users/yutianyang/miniconda3/bin/python -m backtest.evaluate_dsr --split-version v1

=================================================================
  MULTIPLE-TESTING EVALUATION (Heuristic Approximation)
=================================================================

  NOTE: This is an approximate screen using the expected
  maximum Sharpe threshold SR* = sqrt(2 * ln(N)), NOT the
  full Bailey-López de Prado Deflated Sharpe Ratio.

  Trials (N):           2
  Threshold SR*:        1.1774
  Best Sharpe:          -0.1784
  Worst Sharpe:         -0.1784
  Mean Sharpe:          -0.1784

  Best strategy DOES NOT SURVIVE multiple-testing correction
  (-0.1784 <= 1.1774)

  Rank     Sharpe  Strategy
  ------ --------  ----------------------------------------
  1       -0.1784  sma_crossover (04d89e60)
  2       -0.1784  sma_crossover (92eb97ae)

=================================================================


2026-04-16T06:08:37Z [INFO] Ensured 'runs' table exists with Phase 1A schema

$ /Users/yutianyang/miniconda3/bin/python -m backtest.evaluate_dsr --split-version v1 --run-type single_run

=================================================================
  MULTIPLE-TESTING EVALUATION (Heuristic Approximation)
=================================================================

  NOTE: This is an approximate screen using the expected
  maximum Sharpe threshold SR* = sqrt(2 * ln(N)), NOT the
  full Bailey-López de Prado Deflated Sharpe Ratio.

  Trials (N):           9
  Threshold SR*:        2.0963
  Best Sharpe:          1.0466
  Worst Sharpe:         0.0000
  Mean Sharpe:          0.5277

  Best strategy DOES NOT SURVIVE multiple-testing correction
  (1.0466 <= 2.0963)

  Rank     Sharpe  Strategy
  ------ --------  ----------------------------------------
  1        1.0466  sma_crossover (14af73e6)
  2        1.0466  sma_crossover (29d531c0)
  3        1.0466  sma_crossover (a45204b5)
  4        1.0267  sma_crossover (5ef19628)
  5        0.2993  momentum (fe1807a5)
  6        0.1415  sma_crossover (c866f891)
  7        0.1415  sma_crossover (89732640)
  8        0.0000  sma_crossover (6445c6a0)
  9        0.0000  sma_crossover (7112415b)

=================================================================


2026-04-16T06:08:37Z [INFO] Ensured 'runs' table exists with Phase 1A schema

$ /Users/yutianyang/miniconda3/bin/python -m backtest.evaluate_dsr --split-version v1 --strategy sma_crossover

=================================================================
  MULTIPLE-TESTING EVALUATION (Heuristic Approximation)
=================================================================

  NOTE: This is an approximate screen using the expected
  maximum Sharpe threshold SR* = sqrt(2 * ln(N)), NOT the
  full Bailey-López de Prado Deflated Sharpe Ratio.

  Trials (N):           2
  Threshold SR*:        1.1774
  Best Sharpe:          -0.1784
  Worst Sharpe:         -0.1784
  Mean Sharpe:          -0.1784

  Best strategy DOES NOT SURVIVE multiple-testing correction
  (-0.1784 <= 1.1774)

  Rank     Sharpe  Strategy
  ------ --------  ----------------------------------------
  1       -0.1784  sma_crossover (04d89e60)
  2       -0.1784  sma_crossover (92eb97ae)

=================================================================


2026-04-16T06:08:38Z [INFO] Ensured 'runs' table exists with Phase 1A schema

D12 CLI report semantics checks

                                              check status detail
0                  report includes number of trials   PASS
1            report includes best/worst/mean Sharpe   PASS
2                         report includes threshold   PASS
3      report includes survive/not-survive decision   PASS
4                  report includes strategy ranking   PASS
5  report explicitly says heuristic and approximate   PASS
6                    report says it is not full DSR   PASS

## N. D12 Final Acceptance Summary

D12 passes when formula math, decision logic, registry query filters, NULL-Sharpe exclusion, CLI output, and heuristic disclaimer checks all pass.

In [21]:
d12_rows = [
    check_row("threshold math", D12_ACCEPTANCE.get("threshold_math", False)),
    check_row("decision logic", D12_ACCEPTANCE.get("decision_logic", False)),
    check_row("registry query filters", D12_ACCEPTANCE.get("registry_query_filters", False)),
    check_row("NULL Sharpe exclusion", D12_ACCEPTANCE.get("null_sharpe_exclusion", False)),
    check_row("CLI report output", D12_ACCEPTANCE.get("cli_report_output", False)),
    check_row("explicit heuristic disclaimer", D12_ACCEPTANCE.get("explicit_heuristic_disclaimer", False)),
]
display_check_table(d12_rows, "D12 final acceptance summary")
print("D12 ACCEPTED as a heuristic multiple-testing screen, not a production-grade formal DSR implementation.")

D12 final acceptance summary

                           check status detail
0                 threshold math   PASS
1                 decision logic   PASS
2         registry query filters   PASS
3          NULL Sharpe exclusion   PASS
4              CLI report output   PASS
5  explicit heuristic disclaimer   PASS

D12 ACCEPTED as a heuristic multiple-testing screen, not a production-grade formal DSR implementation.

## O. D13 Additional Baselines Acceptance

D13 acceptance checks that `volatility_breakout` and `mean_reversion` behave like normal Phase 1B strategies: discoverable by the engine, runnable in single-run and walk-forward modes, isolated in registry/artifacts, and sane relative to the existing baselines.

In [22]:
from backtest.engine import (
    STRATEGY_REGISTRY,
    _ensure_strategies_loaded,
    run_backtest,
    run_walk_forward,
)
from strategies.baseline.mean_reversion import MeanReversion
from strategies.baseline.momentum import Momentum
from strategies.baseline.sma_crossover import SMACrossover
from strategies.baseline.volatility_breakout import VolatilityBreakout

D13_ACCEPTANCE = {}
D13_SINGLE_START = datetime(2024, 1, 1, tzinfo=timezone.utc)
D13_SINGLE_END = datetime(2024, 6, 30, 23, tzinfo=timezone.utc)
D13_CASH = 10_000.0
D13_FEE_RATE = 0.0007

D13_NEW_STRATEGIES = {
    "volatility_breakout": VolatilityBreakout,
    "mean_reversion": MeanReversion,
}
D13_ALL_BASELINES = {
    "sma_crossover": SMACrossover,
    "momentum": Momentum,
    **D13_NEW_STRATEGIES,
}


def finite_number(value):
    return value is not None and np.isfinite(float(value))


def as_utc_timestamp(value):
    ts = pd.Timestamp(value)
    return ts.tz_localize("UTC") if ts.tzinfo is None else ts.tz_convert("UTC")


def load_trade_csv(run_id):
    path = RESULTS_DIR / f"trades_{run_id}.csv"
    if not path.exists():
        return path, pd.DataFrame()
    trades = pd.read_csv(
        path,
        parse_dates=[
            "entry_signal_time_utc", "entry_time_utc",
            "exit_signal_time_utc", "exit_time_utc",
        ],
    )
    for col in [
        "entry_signal_time_utc", "entry_time_utc",
        "exit_signal_time_utc", "exit_time_utc",
    ]:
        trades[col] = pd.to_datetime(trades[col], utc=True)
    return path, trades

## P. Strategy Discovery

Confirms that engine auto-discovery sees all four baseline strategies, including the two D13 additions.

In [23]:
_ensure_strategies_loaded()
strategy_registry_df = pd.DataFrame([
    {"strategy_name": name, "class": cls.__name__, "module": cls.__module__}
    for name, cls in sorted(STRATEGY_REGISTRY.items())
])
display(strategy_registry_df)

expected_discovery = set(D13_ALL_BASELINES)
discovery_checks = [
    check_row("all four baseline strategies discovered", expected_discovery <= set(STRATEGY_REGISTRY)),
    check_row("volatility_breakout maps to VolatilityBreakout", STRATEGY_REGISTRY.get("volatility_breakout") is VolatilityBreakout),
    check_row("mean_reversion maps to MeanReversion", STRATEGY_REGISTRY.get("mean_reversion") is MeanReversion),
]
display_check_table(discovery_checks, "D13 strategy discovery checks")
D13_ACCEPTANCE["discovery"] = True

         strategy_name               class                                   module
0       mean_reversion       MeanReversion       strategies.baseline.mean_reversion
1             momentum            Momentum             strategies.baseline.momentum
2        sma_crossover        SMACrossover        strategies.baseline.sma_crossover
3  volatility_breakout  VolatilityBreakout  strategies.baseline.volatility_breakout

D13 strategy discovery checks

                                            check status detail
0         all four baseline strategies discovered   PASS
1  volatility_breakout maps to VolatilityBreakout   PASS
2            mean_reversion maps to MeanReversion   PASS

## Q. Single-Run Spot Checks

Runs each D13 strategy on a fixed 2024 H1 range and checks that registry rows, trade artifacts, and finite metrics are produced.

In [24]:
D13_SINGLE_RESULTS = {}
single_rows = []

for strategy_name, strategy_cls in D13_NEW_STRATEGIES.items():
    result = run_backtest(
        strategy_cls=strategy_cls,
        start_date=D13_SINGLE_START,
        end_date=D13_SINGLE_END,
        parquet_path=PARQUET_PATH,
        cash=D13_CASH,
        write_registry=True,
    )
    D13_SINGLE_RESULTS[strategy_name] = result

    registry = read_runs_query("""
        SELECT *
        FROM runs
        WHERE run_id = ?
    """, params=(result.run_id,))
    trade_path, trades = load_trade_csv(result.run_id)

    single_rows.append({
        "strategy_name": strategy_name,
        "run_id": result.run_id,
        "warmup_bars": result.warmup_bars,
        "result_trades": len(result.trades),
        "registry_rows": len(registry),
        "registry_total_trades": int(registry.iloc[0]["total_trades"]) if len(registry) else None,
        "trade_csv_exists": trade_path.exists(),
        "trade_csv_rows": len(trades),
        "sharpe_ratio": result.metrics["sharpe_ratio"],
        "total_return": result.metrics["total_return"],
        "max_drawdown": result.metrics["max_drawdown"],
    })

single_run_df = pd.DataFrame(single_rows)
display(single_run_df)

single_checks = [
    check_row("both D13 strategies completed", set(single_run_df["strategy_name"]) == set(D13_NEW_STRATEGIES)),
    check_row("each single-run has registry row", (single_run_df["registry_rows"] == 1).all()),
    check_row("each single-run produces trades", (single_run_df["result_trades"] > 0).all(), single_run_df.to_dict(orient="records")),
    check_row("trade CSV exists for each single-run", single_run_df["trade_csv_exists"].all()),
    check_row("CSV rows match result trades", (single_run_df["trade_csv_rows"] == single_run_df["result_trades"]).all()),
    check_row("registry total_trades matches result trades", (single_run_df["registry_total_trades"] == single_run_df["result_trades"]).all()),
    check_row("single-run metrics are finite", single_run_df[["sharpe_ratio", "total_return", "max_drawdown"]].map(finite_number).all().all()),
    check_row("new strategy Sharpe is not suspiciously high", (single_run_df["sharpe_ratio"] < 2.0).all(), single_run_df[["strategy_name", "sharpe_ratio"]].to_dict(orient="records")),
]
display_check_table(single_checks, "D13 single-run checks")
D13_ACCEPTANCE["single_run"] = True

2026-04-16T06:37:02Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2024-01-01, 2024-06-30], run_id=4f51640e
2026-04-16T06:37:02Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:02Z [INFO]   Loaded 4368 bars: 2024-01-01 00:00:00 to 2024-06-30 23:00:00
2026-04-16T06:37:02Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:02Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:03Z [INFO] Metrics: return=0.1010 sharpe=0.826 maxDD=0.1474 trades=80 win_rate=0.36 PF=1.12
2026-04-16T06:37:03Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_4f51640e-3cde-4f23-beb2-2a4cc2770cef.csv (80 trades)
2026-04-16T06:37:03Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:03Z [INFO] Inserted run 4f51640e-3cde-4f23-beb2-2a4cc2770cef (strategy: volatility_breakout)
2026-04-16T06:37:03Z [INFO] Backtest complete: 80 trades, return=0.1010, sharpe=0.826, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_4f51640e-3cde-4f23-beb2-2a4cc2770cef.csv
2026-04-16T06:37:03Z [INFO] Starting backtest: strategy=mean_reversion, range=[2024-01-01, 2024-06-30], run_id=893c9858
2026-04-16T06:37:03Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:03Z [INFO]   Loaded 4368 bars: 2024-01-01 00:00:00 to 2024-06-30 23:00:00
2026-04-16T06:37:03Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:03Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:04Z [INFO] Metrics: return=0.2034 sharpe=1.366 maxDD=0.1533 trades=46 win_rate=0.74 PF=1.57
2026-04-16T06:37:04Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_893c9858-b3b5-4f41-b63c-f61513091f96.csv (46 trades)
2026-04-16T06:37:04Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:04Z [INFO] Inserted run 893c9858-b3b5-4f41-b63c-f61513091f96 (strategy: mean_reversion)
2026-04-16T06:37:04Z [INFO] Backtest complete: 46 trades, return=0.2034, sharpe=1.366, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_893c9858-b3b5-4f41-b63c-f61513091f96.csv

,strategy_name,run_id,warmup_bars,result_trades,registry_rows,registry_total_trades,trade_csv_exists,trade_csv_rows,sharpe_ratio,total_return,max_drawdown
0,volatility_breakout,4f51640e-3cde-4f23-beb2-2a4cc2770cef,24,80,1,80,True,80,0.825532,0.101031,0.147404
1,mean_reversion,893c9858-b3b5-4f41-b63c-f61513091f96,48,46,1,46,True,46,1.365857,0.203350,0.153280

D13 single-run checks

,check,status,detail
0,both D13 strategies completed,PASS,
1,each single-run has registry row,PASS,
2,each single-run produces trades,PASS,"[{'strategy_name': 'volatility_breakout', 'run_id': '4f51640e-3cde-4f23-beb2-2a4cc2770cef', 'warmup_bars': 24, 'result_trades': 80, 'registry_rows': 1, 'reg..."
3,trade CSV exists for each single-run,PASS,
4,CSV rows match result trades,PASS,
5,registry total_trades matches result trades,PASS,
6,single-run metrics are finite,PASS,
7,new strategy Sharpe is not suspiciously high,PASS,"[{'strategy_name': 'volatility_breakout', 'sharpe_ratio': 0.8255320000440055}, {'strategy_name': 'mean_reversion', 'sharpe_ratio': 1.3658570447389082}]"

## R. Walk-Forward Window Coverage

Runs walk-forward for each D13 strategy and prints per-window test bars, warmup, trade count, Sharpe, and return. The key check is that no test window is effectively empty or swallowed by warmup.

In [25]:
D13_WF_RESULTS = {}
D13_WINDOW_ROWS = []
raw_for_d13 = pd.read_parquet(PARQUET_PATH)
raw_for_d13["open_time_utc"] = pd.to_datetime(raw_for_d13["open_time_utc"], utc=True)

for strategy_name, strategy_cls in D13_NEW_STRATEGIES.items():
    wf_result = run_walk_forward(
        strategy_cls=strategy_cls,
        parquet_path=PARQUET_PATH,
        cash=D13_CASH,
    )
    D13_WF_RESULTS[strategy_name] = wf_result

    summary_df_d13 = read_runs_query("""
        SELECT *
        FROM runs
        WHERE run_id = ?
    """, params=(wf_result.summary_run_id,))
    assert len(summary_df_d13) == 1, f"Missing D13 summary row for {strategy_name}"

    window_df_d13 = read_runs_query("""
        SELECT *
        FROM runs
        WHERE run_type = 'walk_forward_window'
          AND parent_run_id = ?
        ORDER BY test_start
    """, params=(wf_result.summary_run_id,))

    for _, row in window_df_d13.iterrows():
        test_start = as_utc_timestamp(row["test_start"])
        test_end = as_utc_timestamp(row["test_end"])
        num_test_bars = int(((raw_for_d13["open_time_utc"] >= test_start) & (raw_for_d13["open_time_utc"] <= test_end)).sum())
        D13_WINDOW_ROWS.append({
            "strategy_name": strategy_name,
            "summary_run_id": wf_result.summary_run_id,
            "run_id": row["run_id"],
            "test_start": row["test_start"],
            "test_end": row["test_end"],
            "num_test_bars": num_test_bars,
            "warmup_bars": int(row["warmup_bars"]),
            "total_trades": int(row["total_trades"]),
            "sharpe_ratio": row["sharpe_ratio"],
            "total_return": row["total_return"],
            "max_drawdown": row["max_drawdown"],
        })

D13_WINDOW_DF = pd.DataFrame(D13_WINDOW_ROWS)
display(D13_WINDOW_DF)

zero_trade_summary = D13_WINDOW_DF.groupby("strategy_name")["total_trades"].agg(
    windows="count",
    zero_trade_windows=lambda s: int((s == 0).sum()),
    total_trades="sum",
).reset_index()
display(zero_trade_summary)

coverage_checks = [
    check_row("walk-forward produced windows for both D13 strategies", set(D13_WINDOW_DF["strategy_name"]) == set(D13_NEW_STRATEGIES)),
    check_row("each strategy has same window count as run result", all(
        len(D13_WINDOW_DF[D13_WINDOW_DF["strategy_name"] == name]) == len(result.windows)
        for name, result in D13_WF_RESULTS.items()
    )),
    check_row("every test window has more bars than strategy warmup", (D13_WINDOW_DF["num_test_bars"] > D13_WINDOW_DF["warmup_bars"]).all(), D13_WINDOW_DF.loc[D13_WINDOW_DF["num_test_bars"] <= D13_WINDOW_DF["warmup_bars"]].to_dict(orient="records")),
    check_row("window metrics are finite", D13_WINDOW_DF[["sharpe_ratio", "total_return", "max_drawdown"]].map(finite_number).all().all()),
    check_row("each D13 strategy has at least one walk-forward trade overall", (zero_trade_summary["total_trades"] > 0).all(), zero_trade_summary.to_dict(orient="records")),
]
display_check_table(coverage_checks, "D13 walk-forward coverage checks")
D13_ACCEPTANCE["walk_forward_coverage"] = True

2026-04-16T06:37:04Z [INFO] Walk-forward: 20 windows, volatility_breakout strategy, train=12m test=3m step=3m
2026-04-16T06:37:04Z [INFO]   Window 1/20: train=[2020-01-01, 2020-12-31] test=[2021-01-01, 2021-03-31]
2026-04-16T06:37:04Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2020-01-01, 2021-03-31], run_id=b5130730
2026-04-16T06:37:04Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:04Z [INFO]   Loaded 10925 bars: 2020-01-01 00:00:00 to 2021-03-31 23:00:00
2026-04-16T06:37:04Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:04Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:05Z [INFO] Metrics: return=0.5991 sharpe=1.111 maxDD=0.2407 trades=190 win_rate=0.34 PF=1.25
2026-04-16T06:37:05Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_b5130730-92b8-492d-9fc9-20001575aa55.csv (190 trades)
2026-04-16T06:37:05Z [INFO] Backtest complete: 190 trades, return=0.5991, sharpe=1.111, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_b5130730-92b8-492d-9fc9-20001575aa55.csv
2026-04-16T06:37:05Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_b5130730-92b8-492d-9fc9-20001575aa55.csv (39 trades)
2026-04-16T06:37:05Z [INFO] Metrics: return=0.5991 sharpe=0.567 maxDD=0.2092 trades=39 win_rate=0.38 PF=1.06
2026-04-16T06:37:05Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:05Z [INFO] Inserted run b5130730-92b8-492d-9fc9-20001575aa55 (strategy: volatility_breakout)
2026-04-16T06:37:05Z [INFO]     Window 1: 39 trades, return=0.5991, sharpe=0.567
2026-04-16T06:37:05Z [INFO]   Window 2/20: train=[2020-04-01, 2021-03-31] test=[2021-04-01, 2021-06-30]
2026-04-16T06:37:05Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2020-04-01, 2021-06-30], run_id=ec95ce63
2026-04-16T06:37:05Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:05Z [INFO]   Loaded 10927 bars: 2020-04-01 00:00:00 to 2021-06-30 23:00:00
2026-04-16T06:37:05Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:05Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:06Z [INFO] Metrics: return=0.8144 sharpe=1.377 maxDD=0.2407 trades=187 win_rate=0.35 PF=1.33
2026-04-16T06:37:06Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_ec95ce63-26e1-4862-9291-49a9c35790df.csv (187 trades)
2026-04-16T06:37:06Z [INFO] Backtest complete: 187 trades, return=0.8144, sharpe=1.377, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_ec95ce63-26e1-4862-9291-49a9c35790df.csv
2026-04-16T06:37:06Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_ec95ce63-26e1-4862-9291-49a9c35790df.csv (29 trades)
2026-04-16T06:37:06Z [INFO] Metrics: return=0.8144 sharpe=0.787 maxDD=0.1202 trades=29 win_rate=0.38 PF=1.25
2026-04-16T06:37:06Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:06Z [INFO] Inserted run ec95ce63-26e1-4862-9291-49a9c35790df (strategy: volatility_breakout)
2026-04-16T06:37:06Z [INFO]     Window 2: 29 trades, return=0.8144, sharpe=0.787
2026-04-16T06:37:06Z [INFO]   Window 3/20: train=[2020-07-01, 2021-06-30] test=[2021-07-01, 2021-09-30]
2026-04-16T06:37:06Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2020-07-01, 2021-09-30], run_id=f7a5b94e
2026-04-16T06:37:06Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:06Z [INFO]   Loaded 10950 bars: 2020-07-01 00:00:00 to 2021-09-30 23:00:00
2026-04-16T06:37:06Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:06Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:08Z [INFO] Metrics: return=0.8263 sharpe=1.407 maxDD=0.2303 trades=182 win_rate=0.37 PF=1.33
2026-04-16T06:37:08Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_f7a5b94e-70ba-49a7-9fc1-41322b4bd6f6.csv (182 trades)
2026-04-16T06:37:08Z [INFO] Backtest complete: 182 trades, return=0.8263, sharpe=1.407, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_f7a5b94e-70ba-49a7-9fc1-41322b4bd6f6.csv
2026-04-16T06:37:08Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_f7a5b94e-70ba-49a7-9fc1-41322b4bd6f6.csv (35 trades)
2026-04-16T06:37:08Z [INFO] Metrics: return=0.8263 sharpe=1.507 maxDD=0.0937 trades=35 win_rate=0.46 PF=1.33
2026-04-16T06:37:08Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:08Z [INFO] Inserted run f7a5b94e-70ba-49a7-9fc1-41322b4bd6f6 (strategy: volatility_breakout)
2026-04-16T06:37:08Z [INFO]     Window 3: 35 trades, return=0.8263, sharpe=1.507
2026-04-16T06:37:08Z [INFO]   Window 4/20: train=[2020-10-01, 2021-09-30] test=[2021-10-01, 2021-12-31]
2026-04-16T06:37:08Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2020-10-01, 2021-12-31], run_id=2a5fd704
2026-04-16T06:37:08Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:08Z [INFO]   Loaded 10950 bars: 2020-10-01 00:00:00 to 2021-12-31 23:00:00
2026-04-16T06:37:08Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:08Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:09Z [INFO] Metrics: return=0.8131 sharpe=1.380 maxDD=0.2303 trades=181 win_rate=0.40 PF=1.24
2026-04-16T06:37:09Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_2a5fd704-7e39-476d-a073-ba35a1754037.csv (181 trades)
2026-04-16T06:37:09Z [INFO] Backtest complete: 181 trades, return=0.8131, sharpe=1.380, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_2a5fd704-7e39-476d-a073-ba35a1754037.csv
2026-04-16T06:37:09Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_2a5fd704-7e39-476d-a073-ba35a1754037.csv (41 trades)
2026-04-16T06:37:09Z [INFO] Metrics: return=0.8131 sharpe=-1.558 maxDD=0.2284 trades=41 win_rate=0.34 PF=0.74
2026-04-16T06:37:09Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:09Z [INFO] Inserted run 2a5fd704-7e39-476d-a073-ba35a1754037 (strategy: volatility_breakout)
2026-04-16T06:37:09Z [INFO]     Window 4: 41 trades, return=0.8131, sharpe=-1.558
2026-04-16T06:37:09Z [INFO]   Window 5/20: train=[2021-01-01, 2021-12-31] test=[2022-01-01, 2022-03-31]
2026-04-16T06:37:09Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2021-01-01, 2022-03-31], run_id=954cb7ad
2026-04-16T06:37:09Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:09Z [INFO]   Loaded 10907 bars: 2021-01-01 00:00:00 to 2022-03-31 23:00:00
2026-04-16T06:37:09Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:09Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:10Z [INFO] Metrics: return=0.0024 sharpe=0.201 maxDD=0.3635 trades=181 win_rate=0.38 PF=1.00
2026-04-16T06:37:10Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_954cb7ad-c1d9-4586-bd3f-974199f911a8.csv (181 trades)
2026-04-16T06:37:10Z [INFO] Backtest complete: 181 trades, return=0.0024, sharpe=0.201, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_954cb7ad-c1d9-4586-bd3f-974199f911a8.csv
2026-04-16T06:37:10Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_954cb7ad-c1d9-4586-bd3f-974199f911a8.csv (37 trades)
2026-04-16T06:37:10Z [INFO] Metrics: return=0.0024 sharpe=-0.790 maxDD=0.1751 trades=37 win_rate=0.30 PF=0.81
2026-04-16T06:37:10Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:10Z [INFO] Inserted run 954cb7ad-c1d9-4586-bd3f-974199f911a8 (strategy: volatility_breakout)
2026-04-16T06:37:10Z [INFO]     Window 5: 37 trades, return=0.0024, sharpe=-0.790
2026-04-16T06:37:10Z [INFO]   Window 6/20: train=[2021-04-01, 2022-03-31] test=[2022-04-01, 2022-06-30]
2026-04-16T06:37:10Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2021-04-01, 2022-06-30], run_id=df1314b9
2026-04-16T06:37:10Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:10Z [INFO]   Loaded 10933 bars: 2021-04-01 00:00:00 to 2022-06-30 23:00:00
2026-04-16T06:37:10Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:10Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:12Z [INFO] Metrics: return=-0.1802 sharpe=-0.294 maxDD=0.4088 trades=174 win_rate=0.34 PF=0.90
2026-04-16T06:37:12Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_df1314b9-2988-4321-b22d-e359dee8a6e3.csv (174 trades)
2026-04-16T06:37:12Z [INFO] Backtest complete: 174 trades, return=-0.1802, sharpe=-0.294, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_df1314b9-2988-4321-b22d-e359dee8a6e3.csv
2026-04-16T06:37:12Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_df1314b9-2988-4321-b22d-e359dee8a6e3.csv (31 trades)
2026-04-16T06:37:12Z [INFO] Metrics: return=-0.1802 sharpe=-1.827 maxDD=0.1711 trades=31 win_rate=0.19 PF=0.45
2026-04-16T06:37:12Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:12Z [INFO] Inserted run df1314b9-2988-4321-b22d-e359dee8a6e3 (strategy: volatility_breakout)
2026-04-16T06:37:12Z [INFO]     Window 6: 31 trades, return=-0.1802, sharpe=-1.827
2026-04-16T06:37:12Z [INFO]   Window 7/20: train=[2021-07-01, 2022-06-30] test=[2022-07-01, 2022-09-30]
2026-04-16T06:37:12Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2021-07-01, 2022-09-30], run_id=977a40a0
2026-04-16T06:37:12Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:12Z [INFO]   Loaded 10962 bars: 2021-07-01 00:00:00 to 2022-09-30 23:00:00
2026-04-16T06:37:12Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:12Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:13Z [INFO] Metrics: return=-0.4213 sharpe=-1.114 maxDD=0.5443 trades=186 win_rate=0.32 PF=0.78
2026-04-16T06:37:13Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_977a40a0-c72b-466b-a772-d65c0f0ebde1.csv (186 trades)
2026-04-16T06:37:13Z [INFO] Backtest complete: 186 trades, return=-0.4213, sharpe=-1.114, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_977a40a0-c72b-466b-a772-d65c0f0ebde1.csv
2026-04-16T06:37:13Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_977a40a0-c72b-466b-a772-d65c0f0ebde1.csv (41 trades)
2026-04-16T06:37:13Z [INFO] Metrics: return=-0.4213 sharpe=-2.950 maxDD=0.2530 trades=41 win_rate=0.27 PF=0.50
2026-04-16T06:37:13Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:13Z [INFO] Inserted run 977a40a0-c72b-466b-a772-d65c0f0ebde1 (strategy: volatility_breakout)
2026-04-16T06:37:13Z [INFO]     Window 7: 41 trades, return=-0.4213, sharpe=-2.950
2026-04-16T06:37:13Z [INFO]   Window 8/20: train=[2021-10-01, 2022-09-30] test=[2022-10-01, 2022-12-31]
2026-04-16T06:37:13Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2021-10-01, 2022-12-31], run_id=7e9ba1ca
2026-04-16T06:37:13Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:13Z [INFO]   Loaded 10968 bars: 2021-10-01 00:00:00 to 2022-12-31 23:00:00
2026-04-16T06:37:13Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:13Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:14Z [INFO] Metrics: return=-0.4990 sharpe=-1.603 maxDD=0.5585 trades=178 win_rate=0.28 PF=0.65
2026-04-16T06:37:14Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_7e9ba1ca-b9fd-4891-97f4-33b129d72564.csv (178 trades)
2026-04-16T06:37:14Z [INFO] Backtest complete: 178 trades, return=-0.4990, sharpe=-1.603, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_7e9ba1ca-b9fd-4891-97f4-33b129d72564.csv
2026-04-16T06:37:14Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_7e9ba1ca-b9fd-4891-97f4-33b129d72564.csv (29 trades)
2026-04-16T06:37:14Z [INFO] Metrics: return=-0.4990 sharpe=0.508 maxDD=0.0971 trades=29 win_rate=0.31 PF=1.11
2026-04-16T06:37:14Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:14Z [INFO] Inserted run 7e9ba1ca-b9fd-4891-97f4-33b129d72564 (strategy: volatility_breakout)
2026-04-16T06:37:14Z [INFO]     Window 8: 29 trades, return=-0.4990, sharpe=0.508
2026-04-16T06:37:14Z [INFO]   Window 9/20: train=[2022-01-01, 2022-12-31] test=[2023-01-01, 2023-03-31]
2026-04-16T06:37:14Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2022-01-01, 2023-03-31], run_id=0353db0a
2026-04-16T06:37:14Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:14Z [INFO]   Loaded 10919 bars: 2022-01-01 00:00:00 to 2023-03-31 23:00:00
2026-04-16T06:37:14Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:14Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:16Z [INFO] Metrics: return=-0.1460 sharpe=-0.216 maxDD=0.4168 trades=174 win_rate=0.28 PF=0.90
2026-04-16T06:37:16Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_0353db0a-e4cb-41ad-a40f-6c01fca5fd63.csv (174 trades)
2026-04-16T06:37:16Z [INFO] Backtest complete: 174 trades, return=-0.1460, sharpe=-0.216, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_0353db0a-e4cb-41ad-a40f-6c01fca5fd63.csv
2026-04-16T06:37:16Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_0353db0a-e4cb-41ad-a40f-6c01fca5fd63.csv (37 trades)
2026-04-16T06:37:16Z [INFO] Metrics: return=-0.1460 sharpe=3.650 maxDD=0.1656 trades=37 win_rate=0.30 PF=2.06
2026-04-16T06:37:16Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:16Z [INFO] Inserted run 0353db0a-e4cb-41ad-a40f-6c01fca5fd63 (strategy: volatility_breakout)
2026-04-16T06:37:16Z [INFO]     Window 9: 37 trades, return=-0.1460, sharpe=3.650
2026-04-16T06:37:16Z [INFO]   Window 10/20: train=[2022-04-01, 2023-03-31] test=[2023-04-01, 2023-06-30]
2026-04-16T06:37:16Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2022-04-01, 2023-06-30], run_id=a5569c0a
2026-04-16T06:37:16Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:16Z [INFO]   Loaded 10943 bars: 2022-04-01 00:00:00 to 2023-06-30 23:00:00
2026-04-16T06:37:16Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:16Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:17Z [INFO] Metrics: return=-0.0848 sharpe=-0.069 maxDD=0.3726 trades=179 win_rate=0.26 PF=0.94
2026-04-16T06:37:17Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_a5569c0a-0d32-4ea9-9412-6a87129f23dc.csv (179 trades)
2026-04-16T06:37:17Z [INFO] Backtest complete: 179 trades, return=-0.0848, sharpe=-0.069, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_a5569c0a-0d32-4ea9-9412-6a87129f23dc.csv
2026-04-16T06:37:17Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_a5569c0a-0d32-4ea9-9412-6a87129f23dc.csv (41 trades)
2026-04-16T06:37:17Z [INFO] Metrics: return=-0.0848 sharpe=0.092 maxDD=0.1761 trades=41 win_rate=0.24 PF=1.00
2026-04-16T06:37:17Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:17Z [INFO] Inserted run a5569c0a-0d32-4ea9-9412-6a87129f23dc (strategy: volatility_breakout)
2026-04-16T06:37:17Z [INFO]     Window 10: 41 trades, return=-0.0848, sharpe=0.092
2026-04-16T06:37:17Z [INFO]   Window 11/20: train=[2022-07-01, 2023-06-30] test=[2023-07-01, 2023-09-30]
2026-04-16T06:37:17Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2022-07-01, 2023-09-30], run_id=cee4c167
2026-04-16T06:37:17Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:17Z [INFO]   Loaded 10967 bars: 2022-07-01 00:00:00 to 2023-09-30 23:00:00
2026-04-16T06:37:17Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:17Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:18Z [INFO] Metrics: return=-0.0747 sharpe=-0.067 maxDD=0.2647 trades=186 win_rate=0.26 PF=0.95
2026-04-16T06:37:18Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_cee4c167-459b-45ca-8005-c97c478f43d2.csv (186 trades)
2026-04-16T06:37:18Z [INFO] Backtest complete: 186 trades, return=-0.0747, sharpe=-0.067, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_cee4c167-459b-45ca-8005-c97c478f43d2.csv
2026-04-16T06:37:18Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_cee4c167-459b-45ca-8005-c97c478f43d2.csv (38 trades)
2026-04-16T06:37:18Z [INFO] Metrics: return=-0.0747 sharpe=-4.786 maxDD=0.2032 trades=38 win_rate=0.18 PF=0.13
2026-04-16T06:37:18Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:18Z [INFO] Inserted run cee4c167-459b-45ca-8005-c97c478f43d2 (strategy: volatility_breakout)
2026-04-16T06:37:18Z [INFO]     Window 11: 38 trades, return=-0.0747, sharpe=-4.786
2026-04-16T06:37:18Z [INFO]   Window 12/20: train=[2022-10-01, 2023-09-30] test=[2023-10-01, 2023-12-31]
2026-04-16T06:37:18Z [INFO] Starting backtest: strategy=volatility_breakout, range=[2022-10-01, 2023-12-31], run_id=7813333e
2026-04-16T06:37:18Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:18Z [INFO]   Loaded 10967 bars: 2022-10-01 00:00:00 to 2023-12-31 23:00:00
2026-04-16T06:37:18Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:18Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:20Z [INFO] Metrics: return=0.3293 sharpe=0.973 maxDD=0.2994 trades=189 win_rate=0.27 PF=1.21

,strategy_name,summary_run_id,run_id,test_start,test_end,num_test_bars,warmup_bars,total_trades,sharpe_ratio,total_return,max_drawdown
0,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,b5130730-92b8-492d-9fc9-20001575aa55,2021-01-01T00:00:00Z,2021-03-31T23:00:00Z,2158,24,39,0.566783,0.599122,0.209236
1,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,ec95ce63-26e1-4862-9291-49a9c35790df,2021-04-01T00:00:00Z,2021-06-30T23:00:00Z,2179,24,29,0.786833,0.814387,0.120207
2,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,f7a5b94e-70ba-49a7-9fc1-41322b4bd6f6,2021-07-01T00:00:00Z,2021-09-30T23:00:00Z,2202,24,35,1.506751,0.826328,0.093661
3,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,2a5fd704-7e39-476d-a073-ba35a1754037,2021-10-01T00:00:00Z,2021-12-31T23:00:00Z,2208,24,41,-1.558277,0.813108,0.228445
4,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,954cb7ad-c1d9-4586-bd3f-974199f911a8,2022-01-01T00:00:00Z,2022-03-31T23:00:00Z,2160,24,37,-0.789986,0.002446,0.175058
5,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,df1314b9-2988-4321-b22d-e359dee8a6e3,2022-04-01T00:00:00Z,2022-06-30T23:00:00Z,2184,24,31,-1.827046,-0.180236,0.171112
6,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,977a40a0-c72b-466b-a772-d65c0f0ebde1,2022-07-01T00:00:00Z,2022-09-30T23:00:00Z,2208,24,41,-2.949759,-0.421266,0.252971
7,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,7e9ba1ca-b9fd-4891-97f4-33b129d72564,2022-10-01T00:00:00Z,2022-12-31T23:00:00Z,2208,24,29,0.508498,-0.498997,0.097052
8,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,0353db0a-e4cb-41ad-a40f-6c01fca5fd63,2023-01-01T00:00:00Z,2023-03-31T23:00:00Z,2159,24,37,3.649544,-0.145961,0.165550
9,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,a5569c0a-0d32-4ea9-9412-6a87129f23dc,2023-04-01T00:00:00Z,2023-06-30T23:00:00Z,2184,24,41,0.091853,-0.084837,0.176103
10,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,cee4c167-459b-45ca-8005-c97c478f43d2,2023-07-01T00:00:00Z,2023-09-30T23:00:00Z,2208,24,38,-4.785685,-0.074729,0.203241
11,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,7813333e-df09-4326-9b85-bcd7dedd58e7,2023-10-01T00:00:00Z,2023-12-31T23:00:00Z,2208,24,42,2.176349,0.329315,0.093868
12,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,7ce53050-4618-46a7-8388-69daf11f59ef,2024-01-01T00:00:00Z,2024-03-31T23:00:00Z,2184,24,37,3.220807,0.638903,0.126562
13,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,52d8b29e-cb33-4ad2-a082-9cd453571fbe,2024-04-01T00:00:00Z,2024-06-30T23:00:00Z,2184,24,42,-1.641850,0.061261,0.147404
14,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,76c84eb2-0adf-4838-bbd6-504ba1cd39ea,2024-07-01T00:00:00Z,2024-09-30T23:00:00Z,2208,24,33,-0.070132,0.049647,0.100279
15,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,ef4fc12a-8286-4744-93b7-e97baa75ea6a,2024-10-01T00:00:00Z,2024-12-31T23:00:00Z,2208,24,37,1.185263,0.390206,0.133726
16,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,6faf8bc6-1428-4528-a793-e59ca21c3677,2025-01-01T00:00:00Z,2025-03-31T23:00:00Z,2160,24,28,-1.127138,0.083481,0.158008
17,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,c99805a4-561b-4cf6-b69e-30128e135f6f,2025-04-01T00:00:00Z,2025-06-30T23:00:00Z,2184,24,41,-0.877828,-0.164109,0.131330
18,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,f6287aaa-93b3-43a1-824d-42c7f40822dc,2025-07-01T00:00:00Z,2025-09-30T23:00:00Z,2208,24,38,-1.345083,-0.131423,0.184184
19,volatility_breakout,c0e2e175-31bb-4a0d-9a66-d80cb391678b,f37aa6f0-1b6d-4e4a-b1a3-dbde975e38c4,2025-10-01T00:00:00Z,2025-12-31T23:00:00Z,2208,24,38,-3.908384,-0.290661,0.240430
20,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,d4ec9e87-874e-488d-832b-ca8657b7125b,2021-01-01T00:00:00Z,2021-03-31T23:00:00Z,2158,48,17,1.266499,-0.133345,0.205473
21,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,d82982de-6055-40bb-bada-1a52b8b17100,2021-04-01T00:00:00Z,2021-06-30T23:00:00Z,2179,48,24,0.018136,0.139673,0.227517
22,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,ef92996a-c9d0-4bd8-a02b-1d068e0849ee,2021-07-01T00:00:00Z,2021-09-30T23:00:00Z,2202,48,25,2.355392,0.609474,0.141213
23,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,59c24364-6501-4799-bed9-6be17d5c29ec,2021-10-01T00:00:00Z,2021-12-31T23:00:00Z,2208,48,22,0.668016,0.617480,0.174615
24,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,13f0d844-e7e7-4890-925f-b882a723ad79,2022-01-01T00:00:00Z,2022-03-31T23:00:00Z,2160,48,25,0.044604,0.387152,0.170843
25,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,4def0f83-925e-434b-bf3f-d9806e7e0729,2022-04-01T00:00:00Z,2022-06-30T23:00:00Z,2184,48,22,-1.970516,-0.123135,0.372779
26,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,d7ceff28-feba-425c-b419-19fb43323cfb,2022-07-01T00:00:00Z,2022-09-30T23:00:00Z,2208,48,19,-0.973351,-0.147644,0.199034
27,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,e146dd77-74fa-4be2-89f1-cbd237651140,2022-10-01T00:00:00Z,2022-12-31T23:00:00Z,2208,48,23,-1.088309,-0.375117,0.247354
28,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,a26e7a2a-9482-43cf-a0a2-3c1767bf1958,2023-01-01T00:00:00Z,2023-03-31T23:00:00Z,2159,48,16,0.947918,-0.386834,0.122527
29,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,154e09aa-04cd-4f03-b8de-8ebe1f189d82,2023-04-01T00:00:00Z,2023-06-30T23:00:00Z,2184,48,19,0.444096,-0.373352,0.081092
30,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,90b0caaa-e53c-4efd-8aff-2afc0a1e9b14,2023-07-01T00:00:00Z,2023-09-30T23:00:00Z,2208,48,27,-0.682125,-0.153770,0.115778
31,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,305d0fab-66ef-44f6-8213-082a96c3b503,2023-10-01T00:00:00Z,2023-12-31T23:00:00Z,2208,48,15,0.711004,-0.050183,0.064474
32,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,87a72e39-0db5-4d30-937e-dfc08fd0972d,2024-01-01T00:00:00Z,2024-03-31T23:00:00Z,2184,48,23,3.036204,0.318190,0.109954
33,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,76a5a88f-a2de-4b41-86b8-2190850d945d,2024-04-01T00:00:00Z,2024-06-30T23:00:00Z,2184,48,23,-0.294224,0.240930,0.153280
34,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,bd4a0bb0-d881-4a4a-8ed1-db787dd59abe,2024-07-01T00:00:00Z,2024-09-30T23:00:00Z,2208,48,17,-1.609146,0.013022,0.224379
35,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,eb2fb849-d919-4e2b-ac4a-c3488c2d3a78,2024-10-01T00:00:00Z,2024-12-31T23:00:00Z,2208,48,21,0.868849,0.106847,0.116074
36,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,75195d7b-5f0d-491f-8fa9-0add5ccca12e,2025-01-01T00:00:00Z,2025-03-31T23:00:00Z,2160,48,22,0.620094,0.116531,0.182644
37,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,bb6748d8-e6dd-4764-a9e1-0bbb55feff07,2025-04-01T00:00:00Z,2025-06-30T23:00:00Z,2184,48,17,0.337171,-0.052715,0.094163
38,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,aea8290b-27ed-42fb-8b71-bfdb8766209b,2025-07-01T00:00:00Z,2025-09-30T23:00:00Z,2208,48,21,0.341515,-0.045685,0.047956
39,mean_reversion,5476d291-d87f-43aa-9215-a9d0fc10c3c1,a621f569-8a84-4aef-a27a-da6d919b6679,2025-10-01T00:00:00Z,2025-12-31T23:00:00Z,2208,48,19,-1.635330,0.017576,0.198614

         strategy_name  windows  zero_trade_windows  total_trades
0       mean_reversion       20                   0           417
1  volatility_breakout       20                   0           734

D13 walk-forward coverage checks

,check,status,detail
0,walk-forward produced windows for both D13 strategies,PASS,
1,each strategy has same window count as run result,PASS,
2,every test window has more bars than strategy warmup,PASS,[]
3,window metrics are finite,PASS,
4,each D13 strategy has at least one walk-forward trade overall,PASS,"[{'strategy_name': 'mean_reversion', 'windows': 20, 'zero_trade_windows': 0, 'total_trades': 417}, {'strategy_name': 'volatility_breakout', 'windows': 20, '..."

## S. Walk-Forward Artifact Consistency

Reuses the D11 artifact isolation checks for the two new strategies: persisted test-window CSVs must match registry `total_trades`, and entries/exits must stay inside each window.

In [26]:
artifact_rows = []
leak_rows = []

for _, row in D13_WINDOW_DF.iterrows():
    trade_path, trades = load_trade_csv(row["run_id"])
    registry_total = int(row["total_trades"])
    test_start = as_utc_timestamp(row["test_start"])
    test_end = as_utc_timestamp(row["test_end"])

    csv_expected = registry_total > 0
    row_summary = {
        "strategy_name": row["strategy_name"],
        "run_id": row["run_id"],
        "registry_total_trades": registry_total,
        "trade_csv_exists": trade_path.exists(),
        "trade_csv_required": csv_expected,
        "csv_rows": len(trades),
        "row_count_matches_registry": (len(trades) == registry_total) if trade_path.exists() else (registry_total == 0),
        "all_entries_in_test": True,
        "all_exits_in_test": True,
    }

    if registry_total > 0 and not trade_path.exists():
        row_summary["all_entries_in_test"] = False
        row_summary["all_exits_in_test"] = False
        leak_rows.append({"run_id": row["run_id"], "issue": "missing required trade CSV"})
    elif len(trades) > 0:
        entry_ok = (trades["entry_time_utc"] >= test_start) & (trades["entry_time_utc"] <= test_end)
        exit_ok = (trades["exit_time_utc"] >= test_start) & (trades["exit_time_utc"] <= test_end)
        row_summary["all_entries_in_test"] = bool(entry_ok.all())
        row_summary["all_exits_in_test"] = bool(exit_ok.all())
        leaked = trades[~(entry_ok & exit_ok)].copy()
        if len(leaked) > 0:
            leaked.insert(0, "strategy_name", row["strategy_name"])
            leaked.insert(1, "run_id", row["run_id"])
            leaked.insert(2, "test_start", test_start)
            leaked.insert(3, "test_end", test_end)
            leak_rows.extend(leaked[[
                "strategy_name", "run_id", "test_start", "test_end", "trade_id",
                "entry_signal_time_utc", "entry_time_utc",
                "exit_signal_time_utc", "exit_time_utc",
            ]].to_dict(orient="records"))

    artifact_rows.append(row_summary)

D13_ARTIFACT_DF = pd.DataFrame(artifact_rows)
display(D13_ARTIFACT_DF)

D13_LEAK_DF = pd.DataFrame(leak_rows)
if len(D13_LEAK_DF) > 0:
    display(D13_LEAK_DF.head(30))

artifact_checks = [
    check_row("trade CSV exists whenever registry total_trades > 0", bool((D13_ARTIFACT_DF["trade_csv_exists"] | ~D13_ARTIFACT_DF["trade_csv_required"]).all())),
    check_row("CSV row counts match registry total_trades", bool(D13_ARTIFACT_DF["row_count_matches_registry"].all()), D13_ARTIFACT_DF.loc[~D13_ARTIFACT_DF["row_count_matches_registry"]].to_dict(orient="records")),
    check_row("all trade entries are inside their test window", bool(D13_ARTIFACT_DF["all_entries_in_test"].all()), f"leaked_rows={len(D13_LEAK_DF)}"),
    check_row("all trade exits are inside their test window", bool(D13_ARTIFACT_DF["all_exits_in_test"].all()), f"leaked_rows={len(D13_LEAK_DF)}"),
]
display_check_table(artifact_checks, "D13 walk-forward artifact consistency checks")
D13_ACCEPTANCE["artifact_consistency"] = True

,strategy_name,run_id,registry_total_trades,trade_csv_exists,trade_csv_required,csv_rows,row_count_matches_registry,all_entries_in_test,all_exits_in_test
0,volatility_breakout,b5130730-92b8-492d-9fc9-20001575aa55,39,True,True,39,True,True,True
1,volatility_breakout,ec95ce63-26e1-4862-9291-49a9c35790df,29,True,True,29,True,True,True
2,volatility_breakout,f7a5b94e-70ba-49a7-9fc1-41322b4bd6f6,35,True,True,35,True,True,True
3,volatility_breakout,2a5fd704-7e39-476d-a073-ba35a1754037,41,True,True,41,True,True,True
4,volatility_breakout,954cb7ad-c1d9-4586-bd3f-974199f911a8,37,True,True,37,True,True,True
5,volatility_breakout,df1314b9-2988-4321-b22d-e359dee8a6e3,31,True,True,31,True,True,True
6,volatility_breakout,977a40a0-c72b-466b-a772-d65c0f0ebde1,41,True,True,41,True,True,True
7,volatility_breakout,7e9ba1ca-b9fd-4891-97f4-33b129d72564,29,True,True,29,True,True,True
8,volatility_breakout,0353db0a-e4cb-41ad-a40f-6c01fca5fd63,37,True,True,37,True,True,True
9,volatility_breakout,a5569c0a-0d32-4ea9-9412-6a87129f23dc,41,True,True,41,True,True,True
10,volatility_breakout,cee4c167-459b-45ca-8005-c97c478f43d2,38,True,True,38,True,True,True
11,volatility_breakout,7813333e-df09-4326-9b85-bcd7dedd58e7,42,True,True,42,True,True,True
12,volatility_breakout,7ce53050-4618-46a7-8388-69daf11f59ef,37,True,True,37,True,True,True
13,volatility_breakout,52d8b29e-cb33-4ad2-a082-9cd453571fbe,42,True,True,42,True,True,True
14,volatility_breakout,76c84eb2-0adf-4838-bbd6-504ba1cd39ea,33,True,True,33,True,True,True
15,volatility_breakout,ef4fc12a-8286-4744-93b7-e97baa75ea6a,37,True,True,37,True,True,True
16,volatility_breakout,6faf8bc6-1428-4528-a793-e59ca21c3677,28,True,True,28,True,True,True
17,volatility_breakout,c99805a4-561b-4cf6-b69e-30128e135f6f,41,True,True,41,True,True,True
18,volatility_breakout,f6287aaa-93b3-43a1-824d-42c7f40822dc,38,True,True,38,True,True,True
19,volatility_breakout,f37aa6f0-1b6d-4e4a-b1a3-dbde975e38c4,38,True,True,38,True,True,True
20,mean_reversion,d4ec9e87-874e-488d-832b-ca8657b7125b,17,True,True,17,True,True,True
21,mean_reversion,d82982de-6055-40bb-bada-1a52b8b17100,24,True,True,24,True,True,True
22,mean_reversion,ef92996a-c9d0-4bd8-a02b-1d068e0849ee,25,True,True,25,True,True,True
23,mean_reversion,59c24364-6501-4799-bed9-6be17d5c29ec,22,True,True,22,True,True,True
24,mean_reversion,13f0d844-e7e7-4890-925f-b882a723ad79,25,True,True,25,True,True,True
25,mean_reversion,4def0f83-925e-434b-bf3f-d9806e7e0729,22,True,True,22,True,True,True
26,mean_reversion,d7ceff28-feba-425c-b419-19fb43323cfb,19,True,True,19,True,True,True
27,mean_reversion,e146dd77-74fa-4be2-89f1-cbd237651140,23,True,True,23,True,True,True
28,mean_reversion,a26e7a2a-9482-43cf-a0a2-3c1767bf1958,16,True,True,16,True,True,True
29,mean_reversion,154e09aa-04cd-4f03-b8de-8ebe1f189d82,19,True,True,19,True,True,True
30,mean_reversion,90b0caaa-e53c-4efd-8aff-2afc0a1e9b14,27,True,True,27,True,True,True
31,mean_reversion,305d0fab-66ef-44f6-8213-082a96c3b503,15,True,True,15,True,True,True
32,mean_reversion,87a72e39-0db5-4d30-937e-dfc08fd0972d,23,True,True,23,True,True,True
33,mean_reversion,76a5a88f-a2de-4b41-86b8-2190850d945d,23,True,True,23,True,True,True
34,mean_reversion,bd4a0bb0-d881-4a4a-8ed1-db787dd59abe,17,True,True,17,True,True,True
35,mean_reversion,eb2fb849-d919-4e2b-ac4a-c3488c2d3a78,21,True,True,21,True,True,True
36,mean_reversion,75195d7b-5f0d-491f-8fa9-0add5ccca12e,22,True,True,22,True,True,True
37,mean_reversion,bb6748d8-e6dd-4764-a9e1-0bbb55feff07,17,True,True,17,True,True,True
38,mean_reversion,aea8290b-27ed-42fb-8b71-bfdb8766209b,21,True,True,21,True,True,True
39,mean_reversion,a621f569-8a84-4aef-a27a-da6d919b6679,19,True,True,19,True,True,True

D13 walk-forward artifact consistency checks

                                                 check status         detail
0  trade CSV exists whenever registry total_trades > 0   PASS
1           CSV row counts match registry total_trades   PASS             []
2       all trade entries are inside their test window   PASS  leaked_rows=0
3         all trade exits are inside their test window   PASS  leaked_rows=0

## T. One Manual Trade Audit Per New Strategy

Audits one real trade from each D13 single-run artifact against raw parquet: next-bar-open fill, non-zero volume, and 7 bps per-side commission.

In [27]:
raw_audit = raw_for_d13.set_index("open_time_utc").sort_index()
audit_rows = []

def raw_bar_at(ts):
    ts = as_utc_timestamp(ts)
    assert ts in raw_audit.index, f"Missing raw bar for {ts}"
    return raw_audit.loc[ts]

for strategy_name, result in D13_SINGLE_RESULTS.items():
    trade_path, trades = load_trade_csv(result.run_id)
    assert len(trades) > 0, f"No trade available to audit for {strategy_name}"
    trade = trades.iloc[0]

    entry_signal = as_utc_timestamp(trade["entry_signal_time_utc"])
    entry_time = as_utc_timestamp(trade["entry_time_utc"])
    exit_signal = as_utc_timestamp(trade["exit_signal_time_utc"])
    exit_time = as_utc_timestamp(trade["exit_time_utc"])
    entry_bar = raw_bar_at(entry_time)
    exit_bar = raw_bar_at(exit_time)

    size = abs(float(trade["size"]))
    expected_entry_comm = float(trade["entry_price"]) * size * D13_FEE_RATE
    expected_exit_comm = float(trade["exit_price"]) * size * D13_FEE_RATE

    audit_rows.append({
        "strategy_name": strategy_name,
        "run_id": result.run_id,
        "trade_id": int(trade["trade_id"]),
        "entry_signal_time_utc": entry_signal,
        "entry_time_utc": entry_time,
        "exit_signal_time_utc": exit_signal,
        "exit_time_utc": exit_time,
        "entry_signal_before_fill": entry_signal < entry_time,
        "entry_is_next_bar": entry_time - entry_signal == pd.Timedelta(hours=1),
        "entry_price_matches_open": np.isclose(float(trade["entry_price"]), float(entry_bar["open"]), rtol=0, atol=1e-12),
        "entry_volume_positive": float(entry_bar["volume"]) > 0,
        "exit_signal_before_fill": exit_signal < exit_time,
        "exit_is_next_bar": exit_time - exit_signal == pd.Timedelta(hours=1),
        "exit_price_matches_open": np.isclose(float(trade["exit_price"]), float(exit_bar["open"]), rtol=0, atol=1e-12),
        "exit_volume_positive": float(exit_bar["volume"]) > 0,
        "entry_commission_7bps": np.isclose(float(trade["entry_commission"]), expected_entry_comm, rtol=0, atol=1e-10),
        "exit_commission_7bps": np.isclose(float(trade["exit_commission"]), expected_exit_comm, rtol=0, atol=1e-10),
        "total_commission_matches": np.isclose(float(trade["total_commission"]), float(trade["entry_commission"]) + float(trade["exit_commission"]), rtol=0, atol=1e-10),
    })

D13_AUDIT_DF = pd.DataFrame(audit_rows)
display(D13_AUDIT_DF)

audit_bool_cols = [
    "entry_signal_before_fill", "entry_is_next_bar", "entry_price_matches_open", "entry_volume_positive",
    "exit_signal_before_fill", "exit_is_next_bar", "exit_price_matches_open", "exit_volume_positive",
    "entry_commission_7bps", "exit_commission_7bps", "total_commission_matches",
]
audit_checks = [
    check_row("one trade audited for each D13 strategy", set(D13_AUDIT_DF["strategy_name"]) == set(D13_NEW_STRATEGIES)),
    check_row("all manual trade audit checks pass", D13_AUDIT_DF[audit_bool_cols].all().all(), D13_AUDIT_DF.loc[~D13_AUDIT_DF[audit_bool_cols].all(axis=1)].to_dict(orient="records")),
]
display_check_table(audit_checks, "D13 manual trade audit checks")
D13_ACCEPTANCE["manual_trade_audit"] = True

,strategy_name,run_id,trade_id,entry_signal_time_utc,entry_time_utc,exit_signal_time_utc,exit_time_utc,entry_signal_before_fill,entry_is_next_bar,entry_price_matches_open,entry_volume_positive,exit_signal_before_fill,exit_is_next_bar,exit_price_matches_open,exit_volume_positive,entry_commission_7bps,exit_commission_7bps,total_commission_matches
0,volatility_breakout,4f51640e-3cde-4f23-beb2-2a4cc2770cef,1,2024-01-01 23:00:00+00:00,2024-01-02 00:00:00+00:00,2024-01-02 19:00:00+00:00,2024-01-02 20:00:00+00:00,True,True,True,True,True,True,True,True,True,True,True
1,mean_reversion,893c9858-b3b5-4f41-b63c-f61513091f96,1,2024-01-03 13:00:00+00:00,2024-01-03 14:00:00+00:00,2024-01-04 15:00:00+00:00,2024-01-04 16:00:00+00:00,True,True,True,True,True,True,True,True,True,True,True

D13 manual trade audit checks

                                     check status detail
0  one trade audited for each D13 strategy   PASS
1       all manual trade audit checks pass   PASS     []

## U. Four-Baseline Sanity Table

Runs any missing existing baselines on the same fixed range and compares all four baseline strategies. This is not a profitability target; it is a smoke test for suspiciously inflated Sharpe, explosive trade count, or non-finite metrics.

In [28]:
D13_BASELINE_RESULTS = dict(D13_SINGLE_RESULTS)
for strategy_name, strategy_cls in D13_ALL_BASELINES.items():
    if strategy_name in D13_BASELINE_RESULTS:
        continue
    D13_BASELINE_RESULTS[strategy_name] = run_backtest(
        strategy_cls=strategy_cls,
        start_date=D13_SINGLE_START,
        end_date=D13_SINGLE_END,
        parquet_path=PARQUET_PATH,
        cash=D13_CASH,
        write_registry=True,
    )

baseline_rows = []
for strategy_name, result in D13_BASELINE_RESULTS.items():
    baseline_rows.append({
        "strategy_name": strategy_name,
        "run_id": result.run_id,
        "warmup_bars": result.warmup_bars,
        "trades": len(result.trades),
        "sharpe_ratio": result.metrics["sharpe_ratio"],
        "total_return": result.metrics["total_return"],
        "max_drawdown": result.metrics["max_drawdown"],
    })

D13_BASELINE_DF = pd.DataFrame(baseline_rows).sort_values("strategy_name").reset_index(drop=True)
display(D13_BASELINE_DF)

sanity_checks = [
    check_row("all four baselines represented", set(D13_BASELINE_DF["strategy_name"]) == set(D13_ALL_BASELINES)),
    check_row("all baselines produce at least one trade", (D13_BASELINE_DF["trades"] > 0).all(), D13_BASELINE_DF[["strategy_name", "trades"]].to_dict(orient="records")),
    check_row("trade counts are not explosive", (D13_BASELINE_DF["trades"] < 5_000).all(), D13_BASELINE_DF[["strategy_name", "trades"]].to_dict(orient="records")),
    check_row("metrics are finite", D13_BASELINE_DF[["sharpe_ratio", "total_return", "max_drawdown"]].map(finite_number).all().all()),
    check_row("Sharpe values are not obviously engine-bug inflated", (D13_BASELINE_DF["sharpe_ratio"].abs() < 5.0).all(), D13_BASELINE_DF[["strategy_name", "sharpe_ratio"]].to_dict(orient="records")),
]
display_check_table(sanity_checks, "D13 four-baseline sanity checks")
D13_ACCEPTANCE["sanity"] = True

2026-04-16T06:37:56Z [INFO] Starting backtest: strategy=sma_crossover, range=[2024-01-01, 2024-06-30], run_id=d8ee80b1
2026-04-16T06:37:56Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:56Z [INFO]   Loaded 4368 bars: 2024-01-01 00:00:00 to 2024-06-30 23:00:00
2026-04-16T06:37:56Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:56Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:56Z [INFO] Metrics: return=-0.0067 sharpe=0.141 maxDD=0.3178 trades=56 win_rate=0.38 PF=0.96
2026-04-16T06:37:56Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_d8ee80b1-f026-42a5-baf5-8e9ff64b93ab.csv (56 trades)
2026-04-16T06:37:56Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:56Z [INFO] Inserted run d8ee80b1-f026-42a5-baf5-8e9ff64b93ab (strategy: sma_crossover)
2026-04-16T06:37:56Z [INFO] Backtest complete: 56 trades, return=-0.0067, sharpe=0.141, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_d8ee80b1-f026-42a5-baf5-8e9ff64b93ab.csv
2026-04-16T06:37:56Z [INFO] Starting backtest: strategy=momentum, range=[2024-01-01, 2024-06-30], run_id=59ea66a5
2026-04-16T06:37:56Z [INFO] Loading parquet feed: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/raw/btcusdt_1h.parquet
2026-04-16T06:37:56Z [INFO]   Loaded 4368 bars: 2024-01-01 00:00:00 to 2024-06-30 23:00:00
2026-04-16T06:37:56Z [INFO] Cost model: effective_7bps_per_side (fee=4.0bps + slip=3.0bps = 7.0bps per side)
2026-04-16T06:37:56Z [INFO] Cerebro configured: cash=10000.00, coc=False, coo=False, effective_7bps_per_side, sizer=99%
2026-04-16T06:37:57Z [INFO] Metrics: return=-0.1142 sharpe=-0.686 maxDD=0.2966 trades=61 win_rate=0.38 PF=0.83
2026-04-16T06:37:57Z [INFO] Trade log saved: /Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_59ea66a5-2174-4a26-a8b9-ee44c444a19d.csv (61 trades)
2026-04-16T06:37:57Z [INFO] Ensured 'runs' table exists with Phase 1A schema
2026-04-16T06:37:57Z [INFO] Inserted run 59ea66a5-2174-4a26-a8b9-ee44c444a19d (strategy: momentum)
2026-04-16T06:37:57Z [INFO] Backtest complete: 61 trades, return=-0.1142, sharpe=-0.686, csv=/Users/yutianyang/Documents/GitHub/btc-alpha-pipeline/data/results/trades_59ea66a5-2174-4a26-a8b9-ee44c444a19d.csv

         strategy_name                                run_id  warmup_bars  trades  sharpe_ratio  total_return  max_drawdown
0       mean_reversion  893c9858-b3b5-4f41-b63c-f61513091f96           48      46      1.365857      0.203350      0.153280
1             momentum  59ea66a5-2174-4a26-a8b9-ee44c444a19d           24      61     -0.685641     -0.114175      0.296563
2        sma_crossover  d8ee80b1-f026-42a5-baf5-8e9ff64b93ab           50      56      0.141497     -0.006726      0.317832
3  volatility_breakout  4f51640e-3cde-4f23-beb2-2a4cc2770cef           24      80      0.825532      0.101031      0.147404

D13 four-baseline sanity checks

,check,status,detail
0,all four baselines represented,PASS,
1,all baselines produce at least one trade,PASS,"[{'strategy_name': 'mean_reversion', 'trades': 46}, {'strategy_name': 'momentum', 'trades': 61}, {'strategy_name': 'sma_crossover', 'trades': 56}, {'strateg..."
2,trade counts are not explosive,PASS,"[{'strategy_name': 'mean_reversion', 'trades': 46}, {'strategy_name': 'momentum', 'trades': 61}, {'strategy_name': 'sma_crossover', 'trades': 56}, {'strateg..."
3,metrics are finite,PASS,
4,Sharpe values are not obviously engine-bug inflated,PASS,"[{'strategy_name': 'mean_reversion', 'sharpe_ratio': 1.3658570447389082}, {'strategy_name': 'momentum', 'sharpe_ratio': -0.6856414219105897}, {'strategy_nam..."

## V. D13 Final Acceptance Summary

D13 passes when the new baselines are discoverable, complete single-run and walk-forward checks, preserve artifact isolation, pass one real trade audit each, and look sane beside the existing baselines.

In [29]:
d13_rows = [
    check_row("strategy discovery", D13_ACCEPTANCE.get("discovery", False)),
    check_row("single-run spot checks", D13_ACCEPTANCE.get("single_run", False)),
    check_row("walk-forward window coverage", D13_ACCEPTANCE.get("walk_forward_coverage", False)),
    check_row("artifact consistency", D13_ACCEPTANCE.get("artifact_consistency", False)),
    check_row("manual trade audit", D13_ACCEPTANCE.get("manual_trade_audit", False)),
    check_row("four-baseline sanity", D13_ACCEPTANCE.get("sanity", False)),
]
display_check_table(d13_rows, "D13 final acceptance summary")
print("D13 ACCEPTED: additional baselines preserve Phase 1B discovery, registry, artifact, window, and execution semantics.")

D13 final acceptance summary

                          check status detail
0            strategy discovery   PASS
1        single-run spot checks   PASS
2  walk-forward window coverage   PASS
3          artifact consistency   PASS
4            manual trade audit   PASS
5          four-baseline sanity   PASS

D13 ACCEPTED: additional baselines preserve Phase 1B discovery, registry, artifact, window, and execution semantics.